export default {
  rcActivities: 'Red Cross / Red Crescent Activities',
  langSelectLabel: 'Language: {currentLanguage}',

  headerAppName: 'IFRC GO',
  headerBetaNote: 'This is the beta version of IFRC GO. For issues and feedback on the platform, contact {email}',
  headerCloseLabel: 'close',
  headerMenuResources: 'Resources',
  headerCreateFieldReportLabel: 'Create Field Report',
  headerMenuHome: 'Home',
  headerMenuEmergencies: 'Emergencies',
  headerMenuDeployments: 'Deployments',
  headerMenuPreparedness: 'Preparedness',
  headerSearchLabel: 'Search',
  headerVisitPageTooltip: 'Visit page',
  headerLogoAltText: 'IFRC GO logo',
  headerMenuResourceTooltip: 'Visit Resources page',
  headerCreateFieldReportTooltip: 'Create Field Report',
  headerMenuHomeTooltip: 'Visit Home page',
  headerMenuEmergenciesTooltip: 'Visit Emergencies page',
  headerMenuDeploymentsTooltip: 'Visit Deployments page',
  headerMenuPreparednessTooltip: 'Visit Preparedness page',
  headerSearchPlaceholder: 'Search',

  aboutTitle: 'IFRC Go - About',
  aboutResources: 'Resources',
  aboutDescription: 'GO is a Red Cross Red Crescent platform to connect information on emergency needs with the right response.',
  aboutUserGuidance: 'Go user guidance',
  aboutUserAdministrativeGuide: 'GO User and Administrative Guides',
  aboutUserAdministrativeGuideDescription: 'User guides help to explain the different functions and features of GO. Administrator guides include also back-end functions aimed at people who are helping to manage the site.',
  aboutReferenceMaterials: 'GO Reference Materials',
  aboutReferenceMaterialsDescription: 'These materials provide more information on how and why GO does what it does.',
  aboutVisualGuidelines: 'Visual Guidelines',
  aboutVisualIdentity: 'Visual Identity',
  aboutUserStudy: 'User Studies',
  aboutInformationArchitecture: 'Information Architecture',
  about3WGuidance: '3w guidance',
  about3WLessonLearned: '3w lessons learned',
  aboutPresentation: 'GO presentation materials',
  aboutImStrategy: 'IFRC IM strategy',
  aboutIfrcResources: 'IFRC Resources',
  aboutSurgeServices: 'IFRC Surge Services',
  aboutSurgeCatalogue: 'Catalogue of surge services',
  aboutSurgeNetwork: 'Surge IM network',
  aboutCommunitySurveillance: 'Community Based Surveillance',
  aboutGuidanceMaterial: 'IFRC Guidance Material',
  aboutCashHub: 'Cash Hub',
  aboutCommunityHub: 'Community Engagement Hub',
  aboutDisasterPreparednessCenter: 'Global Disaster Preparedness Centre',
  aboutDataPlaybook: 'Data Playbook',
  aboutOtherResources: 'Other IFRC Resources',
  aboutReferenceCenters: 'Reference Centres',
  aboutMissingMaps: 'Missing Maps',
  aboutReportingSystem: 'Fed-wide Data and Reporting System',
  aboutLearningPlatform: 'Learning Platform',
  aboutContacts: 'Go Contacts',
  aboutFurtherInfo: 'For any further information, please contact',
  aboutAfricaRegion: 'Africa Region',
  aboutAmericaRegion: 'Americas Region',
  aboutAsiaPacificRegion: 'Asia Pacific Region',
  aboutEuropeRegion: 'Europe Region',
  aboutMenaRegion: 'MENA Region',
  aboutGoFunding: 'GO has received dedicated personnel and funding support from:',

  registerTitle: 'IFRC Go - Register',
  registerHeading: 'Register',
  registerFirstName: 'First Name *',
  registerLastName: 'Last Name *',
  registerEmail: 'Email *',
  registerUsername: 'Username *',
  registerCountry: 'Country *',
  registerCity: 'City *',
  registerOrganizationType: 'Organization Type *',
  registerOrganizationName: 'Organization Name *',
  registerDepartment: 'Department',
  registerPosition: 'Position',
  registerPhoneNumber: 'Phone Number',
  registerPassword: 'Password *',
  registerConfirmPassword: 'Confirm Password *',
  registerContactRequest: 'It appears you do not have an official Red Cross Red Crescent email, we will need to verify your status. Please provide the names and email addresses of two RCRC members with active GO accounts for us to contact.',
  registerContactName: 'Contact name',
  registerContactEmail: 'Contact email',
  registerRequestAccess: 'Request Access',
  registerSubmit: 'Register',
  registerSubmitError: 'There are errors in the form. Please correct them before submitting again.',
  registerAccountPresent: 'Already have an account?',
  registerGotoLogin: 'Go to login page',
  registerLogin: 'Log in.',

  loginTitle: 'IFRC Go - Login',
  loginHeader: 'Login',
  loginUsername: 'Username',
  loginPassword: 'Password',
  loginRecoverTitle: 'Recover password',
  loginForgotPassword: 'I forgot my password.',
  loginShowUsernameTitle: 'Show me my username',
  loginForgotUsername: 'I forgot my username only.',
  loginInvalid: 'Invalid username or password',
  loginErrorMessage: 'Error: {message}',
  loginButton: 'Login',
  loginDontHaveAccount: 'Don’t have an account?',
  loginCreateAccountTitle: 'Create new account',
  loginSignUp: 'Sign Up.',

  emergencyTitle: 'IFRC Go - Emergencies',
  emergencyTableTitle: 'Emergencies in the last 30 days',

  fieldReportsTableTitle: 'Field Reports in the last 30 days',
  preparednessTitle: 'IFRC Go - Global Preparedness',
  preparednessHeading: 'Preparedness for Effective Response (PER)',
  preparednessDescription: 'To enable National Societies to fulfil their auxiliary role, in line with the Red Cross and Red Crescent Fundamental Principles, by strengthening local preparedness capacities to ensure timely and effective humanitarian assistance to prevent and alleviate human suffering.',

  homeTitle: 'IFRC Go - Home',
  homeHeading: 'IFRC Disaster Response and Preparedness',
  homeDescription: 'IFRC GO aims to make all disaster information universally accessible and useful to IFRC responders for better decision making.',
  homeSurgeNotification: 'Surge Notifications',
  regionTitle: 'IFRC Go - Region',
  regionTitleSelected: 'IFRC Go - {regionName}',
  regionAppealsTableTitle: 'Active IFRC Operations',
  regionAppealsTableViewAllText: 'View all IFRC operations for {regionName} region',
  regionStatistics: 'Statistics',
  regionRecentEmergencies: 'Recent Emergencies',
  regionEmergenciesTableViewAllText: 'View all Emergencies for {regionName} region',
  region3WTitle: '3W',
  regionKeyFigures: 'Key Figures',
  regionGraphics: 'Graphics',
  regionLinks: 'Links',
  regionContacts: 'Contacts',
  regionOperationTab: 'Operations',
  region3WTab: '3w',
  regionAdditionalInfoTab: 'Additional Information',

  alertTableAlertTypeFact: 'FACT',
  alertTableAlertTypeSims: 'SIMS',
  alertTableAlertTypeEru: 'ERU',
  alertTableAlertTypeDheops: 'DHEOps',
  alertTableAlertTypeHeops: 'HEOps',
  alertTableAlertTypeSurge: 'SURGE',
  alertTableAlertTypeRapidResponse: 'Rapid Response',
  alertTableCategoryInfo: 'Info',
  alertTableCateogryDeployment: 'Deployment',
  alertTableCategoryAlert: 'Alert',
  alertTableCategoryShelter: 'Shelter',
  alertTableCategoryStandDown: 'Stand down',
  alertTableTitle: 'Latest Alerts',
  alertTableError: 'Surge alerts not available.',
  alertTableDate: 'Date',
  alertTableCategory: 'Category',
  alertTableEmergency: 'Emergency',
  alertTableMessage: 'Alert Message',
  alertTableType: 'Type',
  alertTableViewEmergency: 'View Emergency page',
  alertTableViewAllText: 'View all surge alerts',

  highlightedOperationsViewAll: 'View all operations',
  highlightedOperationsTitle: 'Highlighted Operations',
  operationCardLastUpdated: 'Last updated:',
  operationCardTargetedPopulation: 'Targeted Population',
  operationCardDepoloyedUnits: 'Deployed Emergency Response Units',
  operationCardFunding: 'Funding Requirements',
  operationCardDeployed: 'Deployed Surge Personnel',
  operationCardFundingCoverage: 'Funding Coverage',

  countryListInRegion: ' Countries in this Region',
  countryListViewActiveOnly: 'View only active operations',
  countryListActiveOperation: 'Active Operation',
  countryListActiveOperations: 'Active Operations',

  emergenciesTableError: 'Latest emergencies not available.',
  emergenciesTableDate: 'Start Date',
  emergenciesTableName: 'Name',
  emergenciesTableDisasterType: 'Disaster Type',
  emergenciesTableGlide: 'Glide',
  emergenciesTableRequestedAmt: 'Requested Amount (CHF)',
  emergenciesTableAffected: '# Affected',
  emergenciesTableCountry: 'Countries',
  emergenciesTableViewAll: 'View all emergencies',

  keyFiguresTitle: 'Key Figures',
  contactsTitle: 'Contacts',
  contactsHeaderName: 'Name',
  contactsHeaderTitle: 'Title',
  contactsHeaderType: 'Type',
  contactsHeaderContact: 'Contact',
  contactsEmailTitle: 'Contact',
  snippetsTitle: 'Additional Graphics',
  linksTitle: 'Additional Links',

  recoverAccountTitle: 'IFRC Go - Recover Password',
  recoverAccountHeading: 'Recover Account',
  recoverAccountEmail: 'Enter the email you used during registration',
  recoverAccountEmailLabel: 'Email',
  recoverAccountSubmitText: 'Recover',

  recoverUsernameTitle: 'IFRC Go - Recover Username',
  recoverUsernameHeading: 'Getting the given Username',
  recoverUsernameEmail: 'Enter the email you used during registration',
  recoverUsernameEmailLabel: 'Email',
  recoverUsernameSubmitText: 'Send me my username',

  presentationDashAppealsTitle: 'Active Operations',

  keyFiguresError: 'Data not available.',
  keyFiguresHeading: 'IFRC Disaster Response and Preparedness',
  keyFiguresStatsOverall: 'Overall stats',
  keyFiguresActiveDrefs: 'Active DREF Operations',
  keyFiguresActiveAppeals: 'Active Emergency Appeals',
  keyFiguresBudget: 'Funding requirements (CHF)',
  keyFiguresAppealsFunding: 'Funding coverage',
  keyFiguresTargetPop: 'Targeted population',
  keyFiguresDrefTitle: 'DREF',
  keyFiguresDrefDescription: 'These are small to medium scale emergency operations funded through the Disaster Relief Emergency Fund (DREF).The DREF provides immediate financial support to National Red Cross and Red Crescent Societies, enabling them to carry out their unique role as first responders after a disaster.',
  keyFigureActiveAppealTitle: 'Emergency Appeal',
  keyFigureActiveAppealDescription: 'These are medium to large scale emergency operations funded through a public appeal for funds.',
  appealsTableTitle: 'Operations Overview',
  appealsTableError: 'Operations data not available.',
  appealsTableStartDate: 'Start Date',
  appealsTableType: 'Type',
  appealsTableCode: 'Code',
  appealsTableName: 'Name',
  appealsTableEmergency: 'Emergency',
  appealsTableDisastertype: 'Disaster Type',
  appealsTableRequestedAmount: 'Requested Amount (CHF)',
  appealsTableFundedAmount: 'Funding (CHF)',
  appealsTableCountry: 'Country',
  appealsTableRowEvent: 'View Emergency',
  appealsTableViewCountry: 'View Country',
  viewAllOperations: 'View all operations',
};
