const about = {
    aboutTitle: 'IFRC GO - About',
    aboutResources: 'Resources',
    aboutDescription: 'GO is a Red Cross Red Crescent platform to connect information on emergency needs with the right response.',
    aboutUserGuidance: 'Go user guidance',
    aboutUserAdministrativeGuide: 'GO User and Administrative Guides',
    aboutUserAdministrativeGuideDescription: 'User guides help to explain the different functions and features of GO. Administrator guides include also back-end functions aimed at people who are helping to manage the site.',
    aboutReferenceMaterials: 'GO Reference Materials',
    aboutReferenceMaterialsDescription: 'These materials provide more information on how and why GO does what it does.',
    aboutGoUserLibrary: 'GO User Library',
    aboutGoBlog: 'GO Blog',
    aboutGoUserStudies: 'GO User Studies',
    aboutGoInfoArchitecture: 'GO Info Architecture',
    aboutGO3wSystemAnalysis: 'GO 3w System Analysis',
    aboutGoWorkplan2022: 'GO Workplan 2022',
    aboutImStrategicDirection: 'IFRC IM Strategic Direction',
    aboutGOUserAnalytics: 'GO User Analytics',
    aboutIfrcResources: 'IFRC Resources',
    aboutSurgeEvents: 'Global Surge events and trainings',
    aboutSurgeServices: 'IFRC Surge Services',
    aboutSurgeNetwork: 'Surge IM network',
    aboutCommunitySurveillance: 'Community Based Surveillance',
    aboutGuidanceMaterial: 'IFRC Guidance Material',
    aboutCashHub: 'Cash Hub',
    aboutCommunityHub: 'Community Engagement Hub',
    aboutDisasterPreparednessCenter: 'Global Disaster Preparedness Centre',
    aboutDataPlaybook: 'Data Playbook',
    aboutOtherResources: 'Other IFRC Resources',
    aboutReferenceCenters: 'Reference Centres',
    aboutMissingMaps: 'Missing Maps',
    aboutReportingSystem: 'Fed-wide Data and Reporting System',
    aboutLearningPlatform: 'Learning Platform',
    aboutContacts: 'Go Contacts',
    aboutFurtherInfo: 'For any further information, please contact',
    // not used -   aboutAfricaRegion: 'Africa Region',
    // not used -   aboutAmericaRegion: 'Americas Region',
    // not used -   aboutAsiaPacificRegion: 'Asia Pacific Region',
    // not used -   aboutEuropeRegion: 'Europe Region',
    // not used -   aboutMenaRegion: 'MENA Region',
    aboutGoFunding: 'GO has received dedicated personnel and funding support from:',
};

export type AboutStrings = typeof about;

export default about;
