const account = {
    accountInformation: 'Account Information',
    accountNotification: 'Notifications',
    accountPerForms: 'PER forms',
    accountThreeWForms: '3W forms',
    accountMyDrefApplications: 'My Dref Applications',
    accountWeeklyDigest: 'Weekly Digest',
    accountWeeklyDigestDescription: 'Select to get a weekly compilation of emergency events based on your preferences.',
    accountNewEmergencies: 'New Emergencies',
    accountNewEmergenciesDescription: 'Select to receive notifications for new emergency events (includes Field Reports, GDACS alerts and WHO Alerts).',
    accountNewOperation: 'New Operations',
    accountNewOperationDescription: 'Select to receive notifications of new IFRC supported emergency operations.',
    accountGeneralAnnouncements: 'General Announcements',
    accountNewRecords: 'New records',
    accountModifiedRecords: 'Modified records',
    accountSurgeAlerts: 'Surge alerts',
    accountDeplyomentMessages: 'Deployment Messages',
    accountsurgeAEM: 'Approaching End of Mission',
    accountPerDueDate: 'PER Due Dates',
    accountRegionAfrica: 'Africa',
    accountRegionAsia: 'Asia Pacific',
    accountRegionMENA: 'MENA',
    accountRegionEurope: 'Europe',
    accountRegionAmerica: 'Americas',
    accountCouldNotLoad: 'Could not load user profile',
    accountError: 'Error:',
    accountUpdated: 'Profile updated',
    accountEditProfile: 'Edit Profile',
    accountChangePassword: 'Change my password',
    accountCancel: 'Cancel',
    accountFirstName: 'First Name',
    accountLastName: 'Last Name',
    accountPhoneNumber: 'Phone Number',
    accountCity: 'City',
    accountOrganization: 'Organization',
    accountOrganizationType: 'Organization Type',
    accountDepartment: 'Department',
    accountPosition: 'Position',
    accountSave: 'Save',
    accountSubmittedReports: 'Submitted Field Reports',
    accountDeleteContact: 'To delete a field report, contact',
    accountDeleteInfo: 'the IM team',
    accountSubscriptionPreferences: 'Subscription preferences',
    accountSubscriptionTypes: 'Notification types',
    accountSubscriptionTypesDescription: 'Set basic notification types.',
    accountRegionalNotification: 'Regional notifications',
    accountRegionalNotificationDescription: 'Select one or more regions to receive notifications about.',
    accountCountryLevel: 'Country-level notifications',
    accountCountryLevelDescription: 'Select one or more countries to receive notifications about.',
    accountDisasterCategory: 'Disaster types',
    accountDisasterCategoryDescription: 'Get notified about new disasters in these categories.',
    accountSurgeNotification: 'Surge Notifications',
    acccountOtherNotification: 'Other Notifications',
    accountUnfollow: 'Unfollow',
    accountCurrentlyFollowing: 'Operations currently following',
    accountTitle: 'IFRC GO - Account',
    accountSubscriptionError: 'Subscriptions coming soon',
    accountSubscriptionTitle: 'Subscriptions',
    accountPerError: 'Please login to view content',
    accountPerTitle: 'PER Forms',
    accountPerPermission: 'Please Log In',
    accountOperationFollowing: 'Operations following',
}

export type AccountStrings = typeof account;

export default account;
kj
