const common = {
    headerAppName: 'IFRC GO',
    headerMenuResources: 'Resources',
    headerCreateAReportLabel: 'Create a Report',
    headerDropdownNewFieldReport: 'New Field Report',
    headerDropdownNewDrefApplication: 'New DREF Application',
    headerDropdownNew3WActivity: 'New 3W Activity',
    headerDropdownNewFlashUpdate: 'New Flash Update',
    headerDropdownCovid19IndicatorTracking: 'COVID-19 Indicator Tracking',
    headerDropdownCovid19NSFinancialOverview: 'COVID-19 NS Financial Overview',
    headerDropdownDrefApplication: 'DREF Application',
    headerMenuHome: 'Home',
    headerMenuEmergencies: 'Emergencies',
    headerMenuSurge: 'Surge',
    headerMenuSurgeTooltip: 'View Deployments Page',
    headerMenuPreparedness: 'Preparedness',
    headerMenuThreeW: '3W',
    headerSearchLabel: 'Search',
    headerVisitPageTooltip: 'Visit page',
    headerLogoAltText: 'IFRC GO logo',
    headerMenuResourceTooltip: 'Visit Resources page',
    headerMenuHomeTooltip: 'Visit Home page',
    headerMenuEmergenciesTooltip: 'Visit Emergencies page',
    headerMenuDeploymentsTooltip: 'Visit Deployments page',
    headerMenuPreparednessTooltip: 'Visit Preparedness page',
    headerMenuThreeWTooltip: 'Visit 3W page',
    headerSearchPlaceholder: 'Search',
    wikiJsLinkGOWiki: 'https://go-wiki.ifrc.org',
    wikiJsLinkUserAccount: 'user_guide/account',
    wikiJsLinkUserContentVisibility: 'user_guide/content_visibility_groups',
    wikiJsLinkRegion: '',
    wikiJsLinkEmergencies: '',
    wikiJsLinkSurge: '',
    wikiJsLinkPreparedness: '',
    wikiJsLinkGlobal3W: '',
    wikiJsLink3WForm: '',
    wikiJsLinkFRForm: '',
    wikiJsLinkCountry3W: '',
    wikiJsLinkRegister: 'user_guide/account',

    // TODO: following can be further divided

    menuRegions: 'Regions',
    menuRegionsTooltip: 'View Regions',

    regionNameAfrica: 'Africa',
    regionNameAsia: 'Asia Pacific',
    regionNameMENA: 'Middle East & North Africa',
    regionNameEurope: 'Europe',
    regionNameAmerica: 'Americas',

    globalStartDate: 'Start Date',
    accountUserGreeting: 'Hello {user}',

    fieldReportsTableTitle: 'Field Reports in the last 30 days',
    preparednessTitle: 'IFRC GO - Global Preparedness',
    preparednessHeading: 'Preparedness for Effective Response (PER)',
    preparednessDescription: 'To enable National Societies to fulfil their auxiliary role, in line with the Red Cross and Red Crescent Fundamental Principles, by strengthening local preparedness capacities to ensure timely and effective humanitarian assistance to prevent and alleviate human suffering.',

    alertTableAlertTypeFact: 'FACT',
    alertTableAlertTypeSims: 'SIMS',
    alertTableAlertTypeEru: 'ERU',
    alertTableAlertTypeDheops: 'DHEOps',
    alertTableAlertTypeHeops: 'HEOps',
    alertTableAlertTypeSurge: 'SURGE',
    alertTableAlertTypeRapidResponse: 'Rapid Response',
    alertTableCategoryInfo: 'Info',
    alertTableCateogryDeployment: 'Deployment',
    alertTableCategoryAlert: 'Alert',
    alertTableCategoryShelter: 'Shelter',
    alertTableCategoryStandDown: 'Stand down',
    alertTableTitle: 'Latest Alerts',
    alertTableError: 'Surge alerts not available.',
    alertTableAlertDate: 'Alert Date',
    alertTableDuration: 'Duration',
    alertTableStartDate: 'Start Date',
    alertTablePosition: 'Position',
    alertTableKeywords: 'Keywords',
    alertTableCountry: 'Country',
    alertTableStatus: 'Status',
    alertTableEmergency: 'Emergency',
    alertTableViewEmergency: 'View Emergency page',
    alertTableViewAllText: 'View all surge alerts',

    highlightedOperationsViewAll: 'View all emergencies (last 30 days)',
    highlightedOperationsTitle: 'Highlighted Operations',
    operationCardLastUpdated: 'Last updated:',
    operationCardTargetedPopulation: 'Targeted Population',
    operationCardDepoloyedUnits: 'Deployed Emergency Response Units',
    operationCardFunding: 'Funding Requirements',
    operationCardIFRCSurgePersonnel: 'IFRC Surge Personnel',
    operationCardNSReportingActivities: 'NS Reporting Activities',
    operationCardDeployed: 'Deployed Surge Personnel',
    operationCardFundingCoverage: '{coverage}% received',
    operationCardFollow: 'Follow',
    operationCardFollowing: 'Following',
    operationCardInvolvesMultipleCountries: 'Involves multiple countries',
    operationCardNoCountryInvolved: 'No Country Involved',

    countryPageTitle: 'IFRC GO - {countryName}',
    countryTitle: 'IFRC GO - Country',
    // not used -   countryListInRegion: ' Countries in this Region',
    // not used -   countryListViewActiveOnly: 'View only active operations',
    countryListActiveOperation: 'IFRC-Supported Operation',
    countryListActiveOperations: 'IFRC-Supported Operations',
    countryPreparednessTitle: 'Preparedness',
    countryOperationsTab: 'Operations',
    country3WTab: '3W',
    countryPreparednessTab: 'Preparedness',
    countryAdditionalInfoTab: 'Additional Data',
    countryCountryPlanTab: 'Country Plan',

    countryPlanTitle: '{countryName} Country Plan',

    keyFiguresTitle: 'Key Figures',
    contactsTitle: 'Contacts',
    contactsHeaderName: 'Name',
    contactsHeaderTitle: 'Title',
    contactsHeaderType: 'Type',
    contactsHeaderContact: 'Contact',
    contactsEmailTitle: 'Contact',
    snippetsTitle: 'Additional Graphics',
    linksTitle: 'Additional Links',

    recoverAccountTitle: 'IFRC GO - Recover Password',
    recoverAccountHeading: 'Recover Account',
    recoverAccountEmail: 'Enter the email you used during registration',
    recoverAccountEmailLabel: 'Email',
    recoverAccountSubmitText: 'Recover',

    recoverUsernameTitle: 'IFRC GO - Recover Username',
    recoverUsernameHeading: 'Getting the given Username',
    recoverUsernameEmail: 'Enter the email you used during registration',
    recoverUsernameEmailLabel: 'Email',
    recoverUsernameSubmitText: 'Send me my username',

    resendValidationTitle: 'IFRC GO - Re-send Validation Email',
    resendValidationUsername: 'Enter the email/username you used during registration',
    // not used -   resendValidationUsernameLabel: 'Username',
    resendValidationSubmitText: 'Re-send',

    activeOperationsTitle: 'Active Operations ({numAppeals})',

    keyFiguresHeading: 'IFRC Disaster Response and Preparedness',
    keyFiguresStatsOverall: 'Overall stats',
    keyFiguresActiveDrefs: 'Active DREF Operations',
    keyFiguresActiveAppeals: 'Active Emergency Appeals',
    keyFiguresBudget: 'Funding requirements (CHF)',
    keyFiguresAppealsFunding: 'Funding coverage',
    keyFiguresTargetPop: 'Targeted population',
    keyFiguresDrefTitle: 'DREF',
    keyFiguresDrefDescription: 'These are small to medium scale emergency operations funded through the Disaster Relief Emergency Fund (DREF).The DREF provides immediate financial support to National Red Cross and Red Crescent Societies, enabling them to carry out their unique role as first responders after a disaster.',
    keyFigureActiveAppealTitle: 'Emergency Appeal',
    keyFigureActiveAppealDescription: 'These are medium to large scale emergency operations funded through a public appeal for funds.',
    appealsTableTitle: 'Operations Overview',
    appealsTableError: 'Operations data not available.',
    appealsTableStartDate: 'Start Date',
    appealsTableType: 'Type',
    appealsTableCode: 'Code',
    appealsTableOperation: 'Operation',
    appealsTableDisastertype: 'Disaster Type',
    appealsTableRequestedAmount: 'Requested Amount',
    appealsTableFundedAmount: 'Funding',
    appealsTableCountry: 'Country',
    // not used -   appealsTableRowEvent: 'View Emergency',
    appealsTableViewCountry: 'View Country',
    viewAllOperations: 'View all operations',

    timeLineChartAppeal: 'Appeals',
    timeLineChartAmount: 'Amount Funded Appeals',
    timeLineChartPeopleTargeted: 'People Targeted',
    timeLineChartDREFs: 'DREFs',
    timeLineChartDrefsAmount: 'Amount Funded DREFs',
    timeLineChartDrefsPeopleTargeted: 'People Targeted',
    timeLineChartError: 'Operations data not available.',
    timeLineChartByMonthTitle: 'DREFS and Appeals Over the Last Year',
    timeLineChartByYearError: 'Annual statistics not available.',
    timeLineChartByYearTitle: 'DREFS and Appeals by Year',
    timeLineChartAggregateError: 'Aggregate data not available.',
    timeLineChartHeading: 'DREFS and Appeals over time',

    regional3WMovementActivity: 'Movement activities',
    regional3WNationalActivity: 'National society activities',
    regional3WSankeyEmpty: 'Not enough data to show the chart',
    regional3WAdd: 'Add',
    budgetOverviewNSOngoingActivity: 'NS with ongoing activities',
    butgetOverviewTotalBudget: 'Total budget',
    peopleOverviewTotalPeople: 'Total number of people reached',
    peopleOverviewTargetedPeople: 'Targeted',
    statusOverviewTotalActivityStatus: 'Total activities by status',
    statusOverviewTotalActivity: 'Total activities',
    exportButtonExporting: 'Exporting...',
    exportButtonExport: 'Export',
    movementFilterOperationType: 'Operation type',
    movementFilterOperationPlaceholder: 'All Operation Types',
    movementFilterProgrammeType: 'Programme type',
    movementFilterProgrammePlaceholder: 'All Programme Types',
    movementFilterSector: 'Sectors of Activity',
    movementFilterSectorPlaceholder: 'All Sectors',
    movementFilterTag: 'Tag',
    movementFilterTagPlaceholder: 'All Tags',
    movementFilterStatus: 'Status',
    movementFilterStatusPlaceholder: 'All Status',
    countryTableDate: 'Start Date',
    countryTableName: 'Name',
    countryTableEmergency: 'Emergency',
    countryTableDisasterType: 'Disaster Type',
    countryTableRequestAmount: 'Requested Amount',
    countryTableFundedAmount: 'Funding (CHF)',
    countryTableActive: 'Active',
    countryTableReportingNS: 'Reporting NS',
    countryTablePrimarySector: 'Activity sector',
    countryTableStatus: 'Status',
    countryTableProgrammeType: 'Type',
    countryTableTargetTotal: 'Total people targeted',
    countryTableReachedTotal: 'Total people reached',
    countryTableBudgetTotal: 'Total budget',
    countryTableProjectCount: '{projectCount} projects',
    countryEditCountry: 'Edit Country',
    // not used -   countryInformScore: 'Inform Score: ',
    nsActivityReporting: 'Reporting NS',
    countryPreparednessPhaseOutcomes: 'PER related uploaded documents',
    nsActivityReportingPlaceholder: 'Select Who (Reporting NS)',
    nsActivitySector: 'Activity',
    nsActivitySectorPlaceholder: 'Select What (Sector)',
    nsActivityCountry: 'Receiving NS',
    nsActivityCountryPlaceholder: 'Select Where (Country)',
    activityDetailsPlanned: 'planned',
    activityDetailsOngoing: 'ongoing',
    activityDetailsCompleted: 'completed',
    activityDetailsActiveNationalCount: 'Active National Societies',
    supportingNSListProjects: '{noOfProjects} projects',

    preparednessHeaderTitle: 'The PER approach',
    preparednessHeaderDetail: 'The PER Approach is a continuous and flexible process that enables National Societies to assess, measure and analyse the strengths and gaps of its preparedness and response mechanism, and ultimately take necessary action to improve it. For more information on the PER Approach select {link}.',
    preparednessMapDownloadTitle: 'Preparedness state',
    // not used -   preparednessOverviewCrumb: 'PER Overview',
    preparednessOverview: 'Preparedness Overview',
    preparednessSummary: 'Preparedness Summary',
    preparednessColumnBar: 'Preparedness Column Bar',
    preparednessWorkPlan: 'Preparedness Work Plan',
    preparednessPhaseOutcomes: 'Preparedness Phase Outcomes',

    prepGlobalTrendsTab: 'Global Summary',
    prepGlobalPerformanceTab: 'Global Performance',
    prepResourceCatalogueTab: 'Catalogue of Resources',
    prepOpLearningTab: 'Operational Learning',

    emergenciesLeftMenuHeading: 'Operations by Type',
    emergenciesLeftMenuTitle: 'IFRC Emergency Operations',
    perPhaseDropdownAllPerPhases: 'All PER Phases',
    perPhaseDropdownOrientation: 'Orientation',
    perPhaseDropdownAssessment: 'Assessment',
    perPhaseDropdownPrioritization: 'Prioritization',
    perPhaseDropdownPlan: 'Plan of action',
    perPhaseDropdownAction: 'Action & Accountability',
    perTypeDropdownAllPerType: 'All PER Types',
    explanationBubbleCurrentPerPhase: 'Current PER phase',
    explanationBubbleOrientation: 'Orientation',
    explanationBubbleAssessment: 'Assessment',
    explanationBubblePrioritization: 'Prioritization & Analysis',
    explanationBubbleWorkPlan: 'Work Plan',
    explanationBubbleAction: 'Action & Accountability',
    explanationBubbleIncomplete: 'Incomplete',
    operationsPopoverClose: 'Close popover',
    operationsPopoverDismiss: 'Dismiss',
    operationsPopoverCurrentPerPhase: 'Current PER process phase',
    // not used -   operationsPopoverCurrentPerType: 'Current PER process type',
    operationsPopoverOrientation: 'Orientation',
    operationsPopoverAssessment: 'Assessment',
    operationsPopoverPrioritization: 'Prioritization',
    operationsPopoverPlan: 'Plan of action',
    operationsPopoverAction: 'Action & Accountability',
    operationsPopoverNoData: 'No data',
    operationsPopoverDate: 'Date of the assessment',
    nationalSocietiesCountries: '({value} countries out of {total})',
    nationalSocietiesTitle: 'National Societies engaged in the PER process',
    globalPreparednessTitle: 'Global Preparedness Highlights',
    globalPreparednessHighPerforming: 'High Performing Components (globally)',
    globalPreparednessTopPrioritized: 'Top Prioritized Components (globally)',
    globalPreparednessPermission: 'You can only see this data if you have the correct permissions.',
    contactPerTitle: 'Contact PER team',
    contactPerDetails: 'Click on the button to contact PER team if you have any questions regarding the PER process.',
    userMenuAccess: 'Access user menu',
    userMenuViewAccount: 'View user account',

    userMenuAccount: 'Account',
    userMenuLogout: 'Logout',
    userMenuLogin: 'Login',
    userMenuRegister: 'Register',

    tableReport: 'Field Reports',
    tableOperation: 'Operations',
    tableEmergency: 'Emergencies',
    tableAlert: 'Surge Alerts',
    tableEru: 'Deployed ERUs',
    tablePersonnel: 'Deployed Personnel',
    tableTitle: 'IFRC GO - {type}',
    tableEmergenciesTitle: 'All {title} Emergencies',
    reportsTableTitle: 'All {title} Field Reports',
    operationsWithEmergency: 'Operation without Emergency Page',
    tableAppealsTitle: 'All {title} {noun}',
    tableAllAlertsTitle: 'All Surge Alerts',
    tableAllEruTitle: 'All Deployed ERUs',
    tableAllPersonnel: 'All Deployed Personnel',
    eruOnly: 'ERU only',
    rrOnly: 'Rapid Response only',
    mixedEruRr: 'ERUs & Rapid Response deployed',

    uhohPageNotFoundTitle: 'IFRC GO - Page not found',
    uhohPageNotFound: 'Page not found',
    uhohPageDescription: 'The requested page does not exist or may have been removed.',

    // not used -   viewPerFormsTitle: 'IFRC GO - PER',
    // not used -   perAccountPoliceStrategy: 'Area 1: Policy and Standards',
    // not used -   perAccountAnalysis: 'Area 2: Analysis and Planning',
    // not used -   perAccountOperationalCapacity: 'Area 3: Operational capacity',
    // not used -   perAccountOperationalCapacity2: 'Area 3: Operational capacity 2',
    // not used -   perAccountCoordination: 'Area 4: Coordination',
    // not used -   perAccountSupport: 'Area 5: Operations support',
    // not used -   perAccountTitle: 'New PER Forms',
    // not used -   perAccountDescription: 'Click on the following links to access the PER forms, where you can select individual National Societies.',
    // not used -   perAccountChooseCountry: 'Choose National Society ',
    perAccountOverview: 'Overview',
    perAccountNewAssessment: 'Start a New Assessment',
    perAccountCompletedAssessments: 'Completed PER Assessments',
    // not used -   perAccountActiveForms: 'Active PER Forms',
    perAccountSelectCountryPlaceholder: 'Select Country',
    perdocumentArea: 'Area',
    // not used -   perdocumentAreas: 'Areas',
    perdocumentOverview: 'Overview',
    perdocumentView: 'View',
    perTableDate: 'Updated Date',
    perTableAssessmentNumber: 'Assessment number',
    perTableFormsIncluded: 'Forms included',
    perDraftEdit: 'Edit',
    perDraftDelete: 'Delete',
    // not used -   perDraftHeading: 'Active drafts',
    mainMapDownloadHeaderTitle: 'Ongoing operations',
    mainMapViewFullscreen: 'View in fullscreen',
    mainMapClose: 'Close the Map',
    mainMapPresentation: 'Presentation Mode',
    emergencyTypesAll: 'All Emergency Types',
    explanationBubbleScalePoints: 'Scale points by',
    explanationBubblePopulationLabel: '# of people targeted',
    explanationBubbleAmountLabel: 'IFRC financial requirements',
    explanationBubbleType: 'Type',
    explanationBubbleEmergencyAppeal: 'Emergency appeal',
    explanationBubbleDref: 'DREF',
    // not used -   explanationBubbleMovement: 'Movement response',
    explanationBubbleEAP: 'Early Action Protocol Activation',
    explanationBubbleMultiple: 'Multiple types',
    explanationBubbleDeployments: 'Deployments',
    operationPopoverClose: 'Close popover',
    operationPopoverDismiss: 'Dismiss',
    operationPopoverPeopleAffected: 'People Targeted',
    operationPopoverAmountRequested: 'Amount Requested (CHF)',
    operationPopoverAmountFunded: 'Amount Funded (CHF)',
    operationPopoverActivity: 'Activity: {activity}',
    operationPopoverStart: 'Start: {start}',
    operationPopoverEnd: 'End: {end}',

    // not used -   editPerFormsTitle: 'IFRC GO - Emergencies',
    footerAboutGo: 'About Go',
    footerAboutGoDesc: 'IFRC GO is a Red Cross Red Crescent platform to connect information on emergency needs with the right response.',
    footerFindOutMore: 'Find out more',
    footerHelpfulLinks: 'Helpful links',
    footerOpenSourceCode: 'Open Source Code',
    footerApiDocumentation: 'API Documentation',
    footerOtherResources: 'Other Resources',
    footerContactUs: 'Contact Us',
    footerIFRC: '© IFRC {year} v{appVersion}',
    perFormTitle: 'IFRC GO - PER Form',
    // not used -   perFormComponentSaveDraft: 'Save as draft',
    // not used -   perFormComponentSubmitForm: 'Submit',
    perFormComponentSave: 'Save',
    // not used -   perFormComponentCreate: 'Create',
    // not used -   perFormExitForm: 'Exit form',
    // not used -   perFormAlertCreated: 'PER Form created, redirecting...',
    // not used -   perFormAlertUpdated: 'PER Form updated, redirecting...',
    // not used -   perFormAlertDeleted: 'PER Form deleted, redirecting...',
    // not used -   perFormsAlertCreated: 'PER Forms created, redirecting...',
    perFormsAlertUpdated: 'PER Forms updated, redirecting...',
    perFormsAlertUpdatedNoRedirect: 'PER Forms updated',
    // not used -   perFormsAlertDeleted: 'PER Forms deleted, redirecting...',
    perOverviewAlertCreated: 'PER Overview created, redirecting...',
    perOverviewAlertUpdated: 'PER Overview updated, redirecting...',
    perOverviewAlertUpdatedNoRedirect: 'PER Overview updated',
    perOverviewAlertDeleted: 'PER Overview deleted, redirecting...',
    perOverviewHeaderCurrent: 'Current PER Assessment',
    perOverviewHeaderPrevious: 'Previous PER Assessment',
    perOverviewHeaderReviews: 'Reviews Planned',
    perOverviewHeaderContact: 'Contact Information',
    perOverviewSaveAndContinue: 'Follow to the forms',
    perOverviewNS: 'National Society*',
    perOverviewEPIBenchmarks: 'EPI benchmarks',
    perOverviewAsmtNumberDescription: 'The number of times that the National Society has gone through PER assessments',
    perOverviewWhatMethod: 'What method has this assessment used',
    perOverviewPrevAssessmentDate: 'Date of previous PER assessment',
    perOverviewPrevAssessmentType: 'Type of previous PER assessment',
    perAssessmentTitle: 'PER Assessment',
    perAssessmentSubmit: 'Final Submit',
    perAssessmentModalMessage: 'You won\'t be able to edit or delete the assessment after you submit it.',
    perAssessmentModalDelete: 'Are you sure you want to delete the assessment?',
    // not used -   overviewFormExit: 'Exit form',
    // not used -   overviewFormHeading: 'WELCOME TO THE PREPAREDNESS FOR EFFECTIVE RESPONSE - OVERVIEW FORM',
    // not used -   overviewFormGeneralInfo: 'General Information',
    // not used -   overviewFormNationalSociety: 'National Society:',
    overviewFormStartDate: 'Date of assessment*',
    overviewFormTypeCapacityAssessment: 'Type of assessment*',
    overviewFormBranchInvolved: 'Branches involved',
    overviewFormFocalPoint: 'NS focal point name',
    overviewFormFocalPointEmail: 'NS focal point email',
    overviewFormFocalPointPhone: 'NS focal point phone number',
    overviewFormPartnerFocalPoint: 'Partner focal point name',
    overviewFormPartnerFocalPointEmail: 'Partner focal point email',
    overviewFormPartnerFocalPointPhone: 'Partner focal point phone number',
    overviewFormPartnerFocalPointOrganization: 'Partner focal point organization name',
    // not used -   overviewFormPreviousPer: 'Have you had a previous PER capacity assessment?',
    // not used -   overviewFormDateOfLastAssessment: 'Date of last capacity assessment',
    // not used -   overviewFormTypeOfLastAssessment: 'Type of last capacity assessment',
    // not used -   overviewFormFocus: 'Focus',
    // not used -   overviewFormFacilitatorInfo: 'Facilitator information',
    // not used -   overviewFormNameLeadFacilitator: 'Name of lead facilitator',
    overviewFormFacilitatorName: 'PER facilitator / team lead name',
    overviewFormFacilitatorEmail: 'PER facilitator / team lead email',
    overviewFormFacilitatorPhone: 'PER facilitator / team lead phone number',
    overviewFormFacilitatorContact: 'PER facilitator / team lead other contact method',
    // not used -   overviewFormEmail: 'E-mail',
    // not used -   overviewFormPhoneNumber: 'Phone number',
    // not used -   overviewFormSkype: 'Skype address',
    overviewFormDateOfMidReview: 'Estimated date of mid-term review',
    overviewFormDateOfNext: 'Estimated date of next assessment',
    // not used -   overviewFormPreparednessHeading: 'WELCOME TO THE PREPAREDNESS FOR EFFECTIVE RESPONSE - OVERVIEW FORM',
    // not used -   overviewFormSaveAsDraft: 'Save as draft',
    // not used -   overviewFormDraftInfo: 'Take care, only Drafts can be edited afterwards!',
    // not used -   overviewFormFinalized: 'Finalized',
    overviewFormIsEPI: 'Do you want to assess the preparedness of your national society for epidemics and pandemics?',
    fieldReportCreate: 'Create Field Report',
    fieldReportUpdate: 'Update Field Report',
    // not used -   fieldReportIncomplete: 'Page {step} of 4 incomplete.',
    // not used -   fieldReportFix: 'To continue please fix:',
    fieldReportSubmit: 'Submit',
    fieldReportContinue: 'Continue',
    // not used -   fieldReportGoBack: 'Go back to previous step',
    // not used -   fieldReportBack: 'Back',
    cmpActionDescriptionLabel: 'Description',
    cmpContactName: 'Name',
    cmpContactTitle: 'Title',
    cmpContactEmail: 'Email',
    cmpContactPhone: 'Phone',
    // not used -   cmpEruAddNew: 'Add new ERU',
    // not used -   cmpEruType: 'Type',
    // not used -   cmpEruStatus: 'Status',
    // not used -   cmpEruUnits: 'Units',
    // not used -   cmpEruDelete: 'Delete ERU',
    // not used -   cmpPlannedStatus: 'Status',
    // not used -   cmpReportSource: 'Specification',
    cmpSourceLabel: 'Source',
    // not used -   fieldReportAsstdByWHO: 'Assisted (WHO):',
    // not used -   fieldReportHealthMinNumAssisted: 'Assisted (Minisry of Health)',
    // not used-    fieldReportImminentDREF: 'Imminent DREF',

    deploymentsTitle: 'IFRC GO - Deployments',
    deploymentsSurgeOverViewTab: 'Surge Overview',
    deploymentsOperationalToolboxTab: 'Operational Toolbox',
    deploymentsCatalogueOfSurgeServicesTab: 'Catalogue Of Surge Services',
    deploymentsDeployedERU: 'Deployed ERUs',
    deploymentsByEmergencies: 'Ongoing Rapid Response Deployments by Emergencies',
    deploymentsOverviewViewAll: 'View All Deployed Personnel',
    deploymentsOverviewTableHeaderEmergency: 'Emergency',
    deploymentsOverviewTableHeaderOrg: 'Deploying Organization',
    deploymentsOverviewTableHeaderSurge: 'Surge Type',
    deploymentsOverviewTableHeaderNo: 'Number of Deployments',
    // not used -   deploymentsDeployedRR: 'Deployed Rapid Response',
    // not used -   deploymentsDeployedRRP: 'Deployed Rapid Response Personnel',
    deploymentsOngoingRR: 'Ongoing Rapid Response Deployments',
    // not used -   deploymentsNSProvidingRRP: 'NS Providing Rapid Response Personnel',
    deploymentsDeplThisYear: 'Deployments This Year',
    // not used -   deploymentsDeployedHeops: 'Deployed HEOPS',
    // not used -   deploymentEruDeploymentTypes: 'ERU Deployment Types',
    deploymentNumberTop5: 'Top 5 NS deploying RR Personnel',
    nationalSocieties: 'National Societies',
    readinessFilteredERUs: 'Filter Ready ERUs',
    readinessResetFilters: 'Reset Filters',
    readinessLastUpdated: 'Last updated {date}',
    readinessReadyErus: ' {numReady} Ready ERUs',
    readinessDeployedErus: '{numDeployed} Deployed ERUs',
    mapComponentExport: 'Export',
    mapFooterDisclaimer: 'The maps used do not imply the expresion of any opinion on the part of the International Federation of Red Cross and Red Crescent Societies or National Societies concerning the legal status of a territory or of its authorities, Data sources: IFRC, OSM contributors, Map box.',
    countryMapDownloadedTitle: 'Movement activities',
    // not used -   mapPopoverTitle: 'Deployments in {name}',
    deploymentsMapHeading: 'Deployments by Country',
    // not used -   deploymentsMapKey: 'Key',
    // not used -   deploymentsMapDeployedTitle: 'Deployed FACT, RDRT/RIT, & HEOPs',
    // not used -   deploymentsMapDeployed: 'Deployed {activeFilter}',
    // not used -   deploymentsMapLegendTitle: 'Emergency Response Units deployed',
    // not used -   deploymentsMapScaleGradient: 'Scale Gradient',
    // not used -   mapPopOverDismiss: 'Dismiss',


    videoCarouselHeading3W: '3W - Who does What, Where.',
    videoCarouselSubHeading3W: 'The "Who does What, Where", or 3W, is a GO platform tool to enhance coordination, improve disaster analysis, and elevate the speed and quality of Red Cross Red Crescent emergency response.',
    videoCarouselHeading3WInstructional: '3W Instructional',
    videoCarouselSubHeading3WInstructional: 'View this video tutorial on how to manage the 3W tool data  (Who, What, Where) and generate useful and visually pleasant information products on the GO Platform - International Federation of Red Cross Red Crescent (IFRC).',
    videoCarouselHeadingFieldReport: 'Field Report COVID-19',
    videoCarouselSubHeadingFieldReport: 'View this video tutorial on how to create a "Field Report" COVID-19 on the GO Platform - International Federation of Red Cross Red Crescent (IFRC).',
    videoCarouselHeadingPER: 'Preparedness for Effective Response Module',
    videoCarouselSubHeadingPER: 'View this video tutorial on how to navigate on the Preparedness for Effective Response (PER) module on the GO Platform - International Federation of Red Cross Red Crescent (IFRC).',
    videoCarouselHeadingSubscribe: 'Subscriptions to User Notifications',
    videoCarouselSubHeadingSubscribe: 'View this video tutorial on how to "Subscribe to User Notifications" on the GO Platform - International Federation of Red Cross Red Crescent (IFRC).',
    videoCarouselHeadingTranslations: 'Translation feature',
    videoCarouselSubHeadingTranslations: 'View this video tutorial on how to use the translation feature on the GO Platform - International Federation of Red Cross Red Crecent (IFRC).',
    videoCarouselHeading3w: '3W (who-what-where) data collection for emergencies',
    videoCarouselHeading3wsub: 'View this video tutorial about the 3W for emergencies tool. The video demonstrates the data collection and display activity of who-what-where data.',
    eruTableTitle: 'Deployed ERUs',
    eruTableNameTitle: 'Owner',
    eruTableNameType: 'Type',
    eruTablePersonnel: 'Personnel Units',
    eruTableEquipment: 'Equipment Units',
    eruTableCountriesDeployed: 'Country Deployed to',
    eruTableEmergency: 'Emergency',
    eruTableViewCountry: 'View Country',
    eruTableViewEmergency: 'View Emergency',
    eruTableViewAll: 'View all deployed ERUs',
    fieldReportsTableTitleDefault: 'Field Reports',
    fieldReportsTableLoginRequired: 'You must be logged in to view field reports. ',
    fieldReportsTableLogin: 'Login',
    fieldReportsTableCreatedAt: 'Created At',
    fieldReportsTableName: 'Name',
    fieldReportsTableEmergency: 'Emergency',
    fieldReportsTableDisasterType: 'Disaster Type',
    fieldReportsTableCountry: 'Countries',
    fieldReportsTableViewAll: 'View Field Report',
    fieldReportsTableViewEmergency: 'View Emergency',
    fieldReportsTableViewAllReports: 'View all field reports',
    fieldReportsTableProblem: '(Performance problems with Export Table)',
    fieldReportsViewAllIn: 'View all field reports in',
    newPasswordField: 'New password',
    newPasswordConfirm: 'Confirm new password',
    newPasswordSubmit: 'Submit',
    personnelTableTitleRR: 'Rapid Response Personnel',
    personnelTableStartDate: 'Start Date',
    personnelTableEndDate: 'End Date',
    personnelTableName: 'Name',
    personnelTableRole: 'Position',
    personnelTableType: 'Type',
    personnelTableFrom: 'Deploying Party',
    personnelTableDeployedTo: 'Deployed To',
    personnelTableEmergency: 'Emergency',
    personnelTableViewCountry: 'View Country',
    personnelTableViewAllDeployed: 'View all deployed personnel',
    preparednessColumnGraphTitle: 'PER components results',
    preparednessOverviewTitle: 'Preparedness For Effective Response Overview',
    preparednessOverviewCurrent: 'Current PER process phase',
    preparednessOverviewOrientation: 'Orientation',
    preparednessOverviewAssessment: 'Assessment',
    preparednessOverviewPrioritization: 'Prioritization',
    preparednessOverviewPlanAction: 'Plan of action',
    preparednessOverviewAction: 'Action and Accountability',
    preparednessOverviewAssessmentDate: 'Date of the assessment',
    preparednessOverviewPerProcessType: 'Type of assessment',
    // not used -   preparednessOverviewFocus: 'Focus',
    // not used -   preparednessOverviewFocalPoint: 'Focal point',
    // not used -   preparednessOverviewEmail: 'Email',
    preparednessOverviewCycle: 'Assessment cycle',
    preparednessSummaryTitle: 'PER Components And Sub-Component results',
    preparednessSummaryHighPerformance: 'High performance',
    preparednessSummaryComponents: 'COMPONENTS',
    preparednessSummaryExists: 'Exists',
    preparednessSummaryNeedsImprovement: 'Needs improvement',
    preparednessSummaryExistsPartially: 'Partially exists',
    preparednessSummaryDoesnotExists: 'Does not exist',
    preparednessSummaryNotReviewed: 'Not reviewed',
    preparednessWorkPlanTitle: 'Preparedness work plan',
    preparednessWorkPlanAdd: 'Add',
    preparednessWorkPlanPrioritization: 'Prioritization:&nbsp;',
    preparednessWorkPlanComponent: 'Component:&nbsp;',
    preparednessWorkPlanBenchmark: 'Benchmark:&nbsp;',
    preparednessWorkPlanActions: 'Actions:&nbsp;',
    preparednessWorkPlanComments: 'Comments:&nbsp;',
    preparednessWorkPlanTimeline: 'Timeline:&nbsp;',
    preparednessWorkPlanFocalPoint: 'Focal Point:&nbsp;',
    preparednessWorkPlanStatus: 'Status:&nbsp;',
    preparednessWorkPlanRequired: 'Required:&nbsp;',
    preparednessWorkPlanPrioritizationLabel: 'Prioritization',
    preparednessWorkPlanComponentLabel: 'Component',
    preparednessWorkPlanBenchmarkLabel: 'Benchmark',
    preparednessWorkPlanActionsLabel: 'Actions',
    preparednessWorkPlanCommentsLabel: 'Comments',
    preparednessWorkPlanTimelineLabel: 'Timeline',
    preparednessWorkPlanFocalPointLabel: 'Focal Point',
    preparednessWorkPlanStatusLabel: 'Status',
    preparednessWorkPlanSupportLabel: 'Support required',
    emergenciesStatsTitle: 'Emergencies',
    emergenciesStatsAffected: 'Affected People',
    emergenciesStatsRequested: 'Requested Amount',
    emergenciesStatsFunding: 'Funding (CHF)',
    // not used -   alertDismissTitle: 'Dismiss alert',
    // not used -   alertDismiss: 'Dismiss',
    confirmModalCancel: 'Cancel',
    confirmModalOk: 'Ok',
    confirmModalConfirm: 'Confirm',

    expandableShowLess: 'Show less',
    expandableShowMore: 'Show more',
    exportButtonExportTable: 'Export Table',
    exportButtonDownloadingProgress: 'Downloading... {progress}%',
    exportButtonTooltip: 'Export data in UTF-8 encoded CSV',

    globalHeaderBannerTitle: 'COVID-19 global situational information and technical guidance available {link}.',
    globalHeaderBannerHere: 'here',
    globalHeaderBannerSurveyTitle: 'Take 5 mins to tell us what you think - {link}',
    globalHeaderBannerSurveyLink: 'GO SURVEY',
    globalHeaderBanner3wTitle: 'NEW: Emergency activity Who-What-Where-When (3w) {link} and data visualisation available for all IFRC-supported operations',
    globalHeaderBanner3wLink: 'form',

    addNewSplit: 'Add New Split',

    projectListTableViewDetails: 'View details',
    projectListTableEdit: 'Edit',
    projectListTableDuplicate: 'Duplicate',
    projectListTableHistory: 'History',
    projectListTableDelete: 'Delete',
    climateChartHeading: 'Climate chart (C°)',
    climateChartKeyClimateHeading: 'Key climate events',
    informIndicatorsTitle: 'Inform indicators',
    keyIndicatorsTitle: 'Key indicators',
    keyIndicatorsPopulation: 'Population',
    keyIndicatorsPopulationPercent: 'Urban pop (% pop)',
    keyIndicatorsGDP: 'GDP',
    keyIndicatorsGNI: 'GNI / capita',
    keyIndicatorsPovertyPercent: 'Poverty (% pop)',
    keyIndicatorsLifeExpectancy: 'Life expentancy',
    keyIndicatorsLiteracy: 'Literacy',
    NSIndicatorsTitle: 'National society indicators',
    NSIndicatorsIncome: 'Income (CHF)',
    NSIndicatorsExpenditure: 'Expenditures (CHF)',
    NSIndicatorsVolunteers: 'Volunteers',
    NSIndicatorsTrained: 'Trained in first aid',
    pastCrisesEventsTitle: 'Past crises events',
    pastCrisesEventsConflict: 'Conflict events',
    pastEpidemicsTitle: 'Past epidemics',
    pastOperationsTitle: 'Past operations',
    pastOperationsPeopleTargeted: 'People targeted',
    pastOperationsFunding: 'Funding requirements',
    populationMapTitle: 'Population map',
    seasonalCalendarTitle: 'Seasonal calendar',
    socialEventsTitle: 'Social events',


    VerboseUrlLoadingMessage: 'Loading page...',

    breadCrumbLogin: 'Login',
    breadCrumbResources: 'Resources',
    breadCrumbAccount: 'Account',
    breadCrumbHome: 'Home',
    breadCrumbSurge: 'Surge',
    // not used -   breadCrumbPERForm: 'PER Form',
    breadCrumbEmergency: 'Emergency',
    breadCrumbEmergencies: 'Emergencies',
    breadCrumbFieldReport: 'Field Report',
    breadCrumbPreparedness: 'Preparedness',
    breadCrumbRegister: 'Register',
    breadCrumbNewFieldReport: 'New Field Report',
    breadCrumbEditFieldReport: 'Edit Field Report',
    breadCrumbGlobalThreeW: 'Global 3W',
    breadCrumbAllThreeW: 'All 3W',
    breadCrumbThreeW: '3W',
    breadCrumbEditProject: 'Edit Project',
    // not used -   breadCrumbProjectDetails: 'Project Details',
    breadCrumbNewThreeW: 'Create new 3W activity',

    countriesEmergencyLinkTooltip: 'View Emergency',
    countriesActiveLabel: 'Active',
    countriesInactiveLabel: 'Inactive',
    countriesAllOperationExportLink: 'View All Operations For {name}',
    countriesStatisticsTitle: 'Statistics',


    passwordChangePageTitle: 'IFRC GO - Change Password',
    passwordChangeHeading: 'Change my password',

    // not used -   perPageTitle: 'IFRC GO - PER',
    countryOverviewTab: 'Country Profile',

    countryProfileKeyDocumentsTitle: 'Key Documents',
    countryProfileExternalSourcesTitle: 'External Sources',
    countryProfileDateRange: 'Date Range',
    countryProfileSearchPlaceholder: 'Search',

    dateFilterHeaderTooltip: 'Filter by {title}',
    dateFilterHeaderFromLabel: 'From',
    dateFilterHeaderToLabel: 'To',
    dateFilterHeaderApplyButtonLabel: 'Apply',

    alertsTableAllLabel: 'All',

    emergenciesDashAllEmergenciesLinkLabel: 'View All Emergencies',

    newPasswordErrorMessage: 'Error: {message}',
    newPasswordSuccessMessage: 'Success! Password changed, redirecting...',
    newPasswordVerifyInputLabel: 'Verify old password',

    userMenuPopupHeading: 'Hello {firstName} {lastName}',

    monthNameJanuary: 'January',
    monthNameFebruary: 'February',
    monthNameMarch: 'March',
    monthNameApril: 'April',
    monthNameMay: 'May',
    monthNameJune: 'June',
    monthNameJuly: 'July',
    monthNameAugust: 'August',
    monthNameSeptember: 'September',
    monthNameOctober: 'October',
    monthNameNovember: 'November',
    monthNameDecember: 'December',

    // not used -   monthNameShortJan: 'Jan',
    // not used -   monthNameShortFeb: 'Feb',
    // not used -   monthNameShortMar: 'Mar',
    // not used -   monthNameShortApr: 'Apr',
    // not used -   monthNameShortMay: 'May',
    // not used -   monthNameShortJun: 'Jun',
    // not used -   monthNameShortJul: 'Jul',
    // not used -   monthNameShortAug: 'Aug',
    // not used -   monthNameShortSep: 'Sep',
    // not used -   monthNameShortOct: 'Oct',
    // not used -   monthNameShortNov: 'Nov',
    // not used -   monthNameShortDec: 'Dec',

    preparednessOverviewContactLabel: 'Contact PER team',
    preparednessPhaseOutcomesUploadLinkLabel: 'Upload',

    formElementErrorRequiredMessage: 'Please fill in the field.',
    formElementErrorDependenciesMessage: 'Please fill in the field.',
    formElementErrorConstMessage: 'Passwords must match.',

    preparednessFactoryNSGraphDataAllCountriesLabel: 'All countries',
    preparednessFactoryNSGraphDataEngagedCountriesLabel: 'Engaged countries',

    privateRouteNotAuthenticatedMessage: 'Please log in to view this page',

    displayTableFilterHeaderOptionTooltipText: 'Filter by {title} - {label}',
    displayTableFilterHeaderLabelTooltipText: 'Filter by {title}',
    displayTableSortHeaderTooltip: 'Sort by {title}',

    exportButtonContainerErrorMessage: 'Error: Could not export data',
    exportButtonContainerExportingMessage: 'Info: Exporting...',

    accountReportListLastUpdated: 'Last Updated: {on}',
    accountProfileFormSubmitButtonTooltip: 'Save',

    ifrcLinkText: '{countryName} on IFRC.org',
    reliefWebLinkText: '{countryName} on reliefweb.int',
    homePageLinkText: '{countryName} RC Homepage',
    fdrsLinkText: 'National Society page on FDRS',

    noDataMessage: 'No data to display.',

    deploymentsPageTitleSurge: 'Surge',
    deploymentsOverviewError: 'Error loading data',
    deploymentsRapidResponse: 'Rapid Response',
    deployementsOverLastYear: 'Ongoing deployments over the last year',

    emergencySourceMessage: 'Source: {link}',
    emergencyFieldReportStatsHeading: 'Key Figures',

    recoverAccountErrorMessage: 'Error: {message}',
    recoverAccountSuccessMessage: 'We have sent an email to your inbox. Redirecting...',

    recoverAccountInvalidEmailMessage: 'Please enter a valid email',

    recoverUsernameSuccessMessage: 'If the given email address exists here, you will find an email in your mailbox...',
    recoverUsernameInvalidEmailMessage: 'Please enter a valid email',

    registerCreateUserDefaultErrorMessage: 'Could not create user',
    registerErrorMessage: 'Error: {message}',
    registerSuccessMessage: 'Success! Verification email sent, redirecting...',

    resendValidationErrorMessage: 'Error: {message}',
    resendValidationSuccessMessage: 'We have sent an email to your inbox. Redirecting...',

    tableNounOperations: 'Operations',
    tableNounDREFs: 'DREFs',
    tableNounAppeals: 'Appeals',

    fieldReportLastUpdatedBy: 'Last updated by {user} on {date}',
    // not used -   fieldReportLastUpdatedOn: 'Last updated on {date}',

    searchSelectTypeToSearch: 'Type to search',
    searchSelectNoOptionsAvailable: 'No options available',

    alertCopyErrorDetails: 'Copy Error Details',

    emptyMessage: 'Data is not available.',
    emptyMessageHelpText: 'Please refresh the browser or visit the platform in a little bit.',

    // dref table headings

    // Submission
    yesLabel: 'Yes',
    noLabel: 'No',

    riskModulePastAndHistoricEvent: 'Past Events And Historical Impact',

    clickToViewEmergencyResponseFramework: 'Click to view Emergency Response Framework',

};

export type CommonStrings = typeof common;

export default common;
