const dref = {
  drefFormAddInterventionLabel: 'Add',
  drefFormUploadAnImageLabel: 'Select an Image',
  drefFormAddCountryLabel: 'Add Country',

  drefFormSaveRequestSuccessMessage: 'DREF Application created/updated successfully',
  drefFormSaveRequestFailureMessage: 'Failed to create/update DREF Application',
  drefFormLoadRequestFailureMessage: 'Failed to load DREF Application',
  drefFormLoadErrorTitle: 'Failed to load DREF Application',
  drefFormLoadErrorDescription: 'There was an error loading the DREF Application',
  drefFormLoadErrorHelpText: 'Please make sure that the application with given id exists and you have the permission to view it',
  drefFormFieldGeneralError: 'Please correct all the errors!',
  drefLoadPdfFailureMessage: 'Failed to create/load PDF',

  drefFormBudgetTemplateLabel: 'Budget template',
  drefFormBudgetTemplateUploadButtonLabel: 'Upload your budget summary',
  drefFormContinueButtonLabel: 'Continue',
  drefFormBackButtonLabel: 'Back',
  drefFormSaveButtonLabel: 'Save',
  drefFormInterventionBudgetLabel: 'Budget',
  drefFormInterventionPersonTargetedLabel: 'Persons Targeted',
  drefFormInterventionPersonAssistedLabel: 'Persons Assisted',
  drefFormIndicatorTitleLabel: 'Title',
  drefFormIndicatorTargetLabel: 'Target',
  drefFormIndicatorActualLabel: 'Actual',
  drefFormAssessmentReportUploadLabel: 'Assessment Report (Optional)',
  drefFormAssessmentReportUploadButtonLabel: 'Upload assesment report',

  drefOperationalLearningPlatformLabel: 'To access lessons from previous operations, please visit the DREF Operational Learning Platform',
  drefFormManMadeEvent: 'Is this a man made event?',
  drefFormPdfTitle: 'DREF APPLICATION',
  drefFormPdfDrefAllocated: 'DREF Allocated',
  drefFormPdfGlideNum: 'Glide No:',
  drefFormPdfAppealNum: 'Appeal No:',
  drefFormPdfPeopleAffected: 'People [affected/ at risk]:',
  drefFormPdfPeopleAssisted: 'People to be assisted',
  drefFormPdfDrefLaunched: 'DREF Launched',
  drefFormPdfDrefEnds: 'Dref Ends:',
  drefFormPdfAffectedAreas: 'Affected areas:',
  drefFormPdfDrescriptionOfTheEvent: 'Description Of The Event',
  drefFormPdfScopeAndScale: 'Scope and Scale',
  drefFormPdfWhatWhereWhen: 'What happened, where and when?',
  drefFormPdfPreviousOperations: 'Previous Operations',
  drefFormPdfAffectSameArea: 'Has a similar event affected the same area(s) in the last 3 years?',
  drefFormPdfAffectedthePopulationTitle: 'Did it affect the same population?',
  drefFormPdfNsRespond: 'Did the NS respond?',
  drefFormPdfNsRequest: 'Did the NS request funding from DREF?',
  drefFormPdfNsFundingDetail: 'If yes, please specify',
  drefFormPdfRecurrentText: 'If you have answered yes to all questions above, justify why the use of DREF for a recurrent event, or how this event should not be considered recurrent',
  drefFormPdfLessonsLearnedTitle: 'Lessons learned',
  drefFormPdfLessonsLearnedDescription: 'Specify how the lessons learnt from these previous operations are being used to mitigate similar challenges in the current operation',
  drefFormPdfMovementPartnersActions: 'Movement Partners Actions related to the current event',
  drefFormPdfIfrc: 'IFRC',
  drefFormPdfIcrc: 'ICRC',
  drefFormPdfPartnerNationalSociety: 'Participating National Societies',
  drefFormPdfNationalOtherActors: 'Other Actors Actions Related To The Current Event',
  drefFormPdfInternationalAssistance: 'Government has requested international assistance',
  drefFormPdfNationalAuthorities: 'National authorities',
  drefFormPdfUNorOtherActors: 'UN or other actors',
  drefFormPdfCoordinationMechanism: 'Are there major coordination mechanisms in place?',
  drefFormPdfNeedsGapsIdentified: 'Needs (Gaps) Identified',
  drefFormPdfTargetingStrategy: 'Targeting Strategy',
  drefFormPdfPeopleAssistedthroughOperation: 'Which groups of people will be assisted through this operation?',
  drefFormPdfSelectionCriteriaRisk: 'What selection criteria has been used to target people at risk?',
  drefFormPdfAssistedPopulation: 'Targeted Population',
  drefFormPdfTargetedPopulation: 'Targeted Population',
  drefFormPdfTargetCommunities: 'For imminent disasters, explain the different triggers to be used (if several thresholds are defined), mention the data sources that verify the risk and potential impacts to targeted communities',
  drefFormPdfImmientDisaster: 'For imminent disaster, explain what is expected to happen, where, when and how is above average ?',
  drefFormPeoplePdfTargetedWithEarlyActions: 'Numbers of persons targeted with early actions',
  drefFormPdfWomen: "Women",
  drefFormPdfMen: 'Men',
  drefFormPdfGirls: 'Girls (under 18)',
  drefFormPdfBoys: 'Boys (under 18)',
  drefFormPdfTotal: 'Total Population',
  drefFormPdfEstimateResponse: 'Estimate',
  drefFormPdfEstimatePeopleDisability: 'Estimated Percentage People with Disability',
  drefFormPdfEstimatedPercentage: 'Estimated Percentage (Urban to Rural)',
  drefFormPdfEstimatedDisplacedPeople: 'Estimated Number of Displaced People on the move (if any)',
  drefFormPdfObjectiveOperation: 'Overall objective of the operation',
  drefFormPdfResponseRationale: 'Response strategy rationale',
  drefFormPdfSupportServices: 'About Support Services',
  drefFormPdfHumanResourceDescription: 'How many volunteers and staff involved in the response? Briefly describe their role.',
  drefFormPdfSurgePersonnelDeployed: 'Will surge personnel be deployed?',
  drefFormPdfLogisticCapacityOfNs: 'What is the logistics capacity of the National Society? If there is procurement, will it be done by the NS or by the IFRC?',
  drefFormPdfSafetyConcerns: 'Are there any safety/security concerns which may impact the implementation of this operation? How will the National Society ensure the safety of the staff, volunteers and community?',
  drefFormPdfPmerDescription: 'Does the NS have PMER capacity? How will monitoring of the operation be organised by both NS and IFRC? If any monitoring trips are planned, clarify purpose and role to be deployed',
  drefFormPdfCommunicationDescription: 'Does the NS have Communications capacity? How will communication on the operation be organised by both NS and IFRC? If any Commissions are planned, clarify purpose and role to be deployed',
  drefFormPdfPlannedIntervention: 'Planned Intervention',
  drefFormPdfNationalSocietyContact: 'National Society contact:',
  drefFormPdfAppealManager: 'IFRC Appeal Manager:',
  drefFormPdfProjectManager: 'IFRC Project Manager',
  drefFormPdfIfrcEmergency: 'IFRC focal point for the emergency',
  drefFormPdfMediaContact: 'Media Contact',
  drefFormPdfReference: 'Click here for the reference',
  drefFormPdfOperationTimeframeSubmission: 'Operation timeframe',
  drefFormPdfAboutSupportServices: 'About Support Services',
  drefFormPdfContactInformation: 'Contact Information',
  drefFormPdfContactDescription: 'For further information, specifically related to this operation please contact:',
  drefFormPdfBudget: 'Budget',
  drefFormPdfTargetPersons: 'Targeted Persons',
  drefFormPdfIndicators: 'Indicators:',
  drefFormPdfPriorityActions: 'Priority Actions:',
  drefFormCaptionLabel: 'Caption',
  drefExportIfrcName: 'International Federation of Red Cross and Red Crescent Societies (IFRC)',
  drefExportTitle: 'DREF Application',
  drefExportDrefAllocated: 'DREF Allocated:',
  drefExportGlideNum: 'Glide Number:',
  drefExportAppealNum: 'Appeal:',
  drefExportPeopleAffected: 'People Affected:',
  drefExportPeopleAtRisk: 'People at risk:',
  drefExportPeopleAssisted: 'People Targeted:',
  drefExportNumPeople: '{num} people',
  drefExportNumMonth: '{num} months',
  drefExportDrefLaunched: 'DREF launched:',
  drefExportOperationTimeframe: 'Operation Timeframe:',
  drefExportAffectedAreas: 'Affected areas:',
  drefExportCrisisCategory: 'Crisis Category:',
  drefExportHazard: 'Hazard:',
  drefExportDrefOperationStartDate: 'Operation Start Date:',
  drefExportDrefEndDateOfOperation: 'Operation End Date:',
  drefExportEventOnset: 'Event Onset:',
  drefExportTargetedAreas: 'Targeted Areas:',
  drefExportScopeAndScaleEvent: 'Scope and Scale',
  drefExportWomen: 'Women:',
  drefExportGirls: 'Girls (under 18):',
  drefExportMen: 'Men:',
  drefExportBoys: 'Boys (under 18):',
  drefExportEstimatePeopleDisability: 'People with disabilities (estimated %)',
  drefExportTotalTargetedPopulation: 'Total targeted population:',
  drefExportEstimatedLocal: 'Rural %',
  drefExportEstimatedUrban: 'Urban %',
  drefExportPercentage: '{num} %',
  drefExportBudgetSummary: 'Budget Summary',
  drefExportBudgetSummaryPlannedOperation: 'Planned Operations',
  drefExportWhatExpectedHappen: 'What is expected to happen?',
  drefExportTargetCommunities: 'Why your National Society is acting now and what criteria is used to launch this operation.',
  drefExportOperationalStrategy: 'Operational Strategy',
  drefExportReference: 'Click here for the reference',
  drefExportAboutSupportServices: 'About Support Services',
  drefExportContactInformation: 'Contact Information',
  drefExportContactDescription: 'For further information, specifically related to this operation please contact:',
  drefExportBudget: 'Budget',
  drefExportTargetPersons: 'Targeted Persons',
  drefExportIndicators: 'Indicators',
  drefExportPriorityActions: 'Priority Actions:',
  drefExportBudgetOverview: 'Budget Overview',
  drefDocumentImportTitle: 'Import from Document',
  drefDocumentImportSlowSuddenLabel: 'Slow/Sudden',
  drefDocumentImportImminentLabel: 'Imminent',
  drefDocumentImportAssessmentLabel: 'Assessment',
  drefFormSubmissionFlow: 'Submission flow',
  drefFormNsRequestDate: 'Date of National Society Application',
  drefFormDateSubmissionToGeneva: 'Date of Submission to GVA',
  drefFormDateOfApproval: 'Date of Approval',
  drefFormPublishingDate: 'Date of Publishing',
  drefFormPublishingDateDescription: 'Added by Regional PMER',
  drefFormAddedByGeneva: 'Added by Geneva',
  drefFormOperationTimeframeSubmission: 'Operation timeframe',
  drefFormOperationTimeframeSubmissionDescription: 'Input number of months',
  drefFormDateOfPublishing: 'Date of publishing',
  drefFormDateOfPublishingDescription: 'Added by the regional office',
  drefFormTrackingData: 'Tracking Data and Contacts',
  drefFormAppealCode: 'Appeal Code',
  drefFormAppealCodeDescription: 'Added by the regional PMER',
  drefFormGlideNum: 'GLIDE number',
  drefFormAppealManager: 'IFRC Appeal Manager:',
  drefFormAppealManagerDescription: 'Added by the regional office',
  drefFormProjectManager: 'IFRC Project Manager:',
  drefFormProjectManagerDescription: 'Added by the regional office',
  drefFormNationalSocietyContact: 'National Society contact:',
  drefFormIfrcEmergency: 'IFRC focal point for the emergency:',
  drefFormMediaContact: 'Media Contact:',
  drefFormSubmissionEndDate: 'End date of Operation',
  drefFormSubmissionEndDateDescription: 'Automatically calculated using the Date of Approval + Operation timeframe',
  drefFormEndDateSubmissionDescription: 'Added by the regional office',
  drefFormMaxThreeHundredCharacters: 'Max 300 characters',

  drefFormCopyFRFailureMessage: 'Failed to get details for selected field report',
  drefFormCopyFRSuccessMessage: 'Successfully copied some data from the selected field report',
  drefFormCopyButtonLabel: 'Copy',

  drefFormMaxFiveHundredCharacters: 'Max 500 characters',
  drefFormMaxEightHundredCharacters: 'Max 800 characters',

  drefFormListOfActivities: 'List of Activities',
  drefTableCreatedOn: 'Created On',
  drefTableCountry: 'Country',
  drefTableAppealNumber: 'Appeal Number',
  drefTableName: 'Name',
  drefTableRegionalTechReview: 'Regional Technical Review',
  drefTableSubmittedToGeneva: 'Submitted to Geneva',
  drefTableLastUpdate: 'Last Update',
  drefTableExport: 'Export',
  drefTableEdit: 'Edit',

  drefInProgressApplications: 'In progress Applications',
  drefApprovedApplications: 'Approved Applications',


  drefFormPageTitle: 'IFRC GO - DREF Application',
  drefFormPageHeading: 'DREF Application',
  drefFormExportLabel: 'Export',

  drefFormTabOperationOverviewLabel: 'Operation Overview',
  drefFormTabEventDetailLabel: 'Event Detail',
  drefFormTabActionsLabel: 'Actions/Needs',
  drefFormTabResponseLabel: 'Operation',
  drefFormTabSubmissionLabel: 'Submission/Contact',

  drefFormSharingHeading: 'Sharing',
  drefFormSharingTitle: 'Share the DREF Application with other Users',
  drefFormSharingDescription: 'The users will be able to view, edit and add other users',
  drefFormInstantShareLabel: 'Create & Share',

  drefFormGenerateTitle: 'Generate title',
  drefFormTitle: 'DREF Title',
  drefFormTitleDescription: 'Add country, type of disaster and location to the title',
  drefFormDescription: 'Description',

  drefFormNationalSocietiesActions: 'Current National Society Actions',
  drefFormNationalSocietiesActionsDescription: 'Please indicate a description of the ongoing response with if possible: Branches involved, number of volunteers/staff involved in actions, assets deployed/distributed, number of people reach. Impact/added value of the NS in the response already ongoing.',
  drefFormNationalSocietiesActionsLabel: 'Select the actions that apply.',
  drefFormMovementPartners: 'Movement Partners Actions Related To The Current Event',
  drefFormIfrc: 'IFRC',
  drefFormIfrcDescription: 'Presence or not of IFRC in country (if not, indicate the cluster covering), support provided for this response, domestic coordination, technical, strategic, surge. Explain what support provided in terms of Secretariat services: PMER, Finance, Admin, HR, Security, logistics, NSD.',
  drefFormIcrc: 'ICRC',
  drefFormIcrcDescription: 'Presence or not of ICRC in country, and support directly provided for this emergency response. Other programs and support provided outside of the scope of this emergency should not be indicated here.',
  drefFormPartnerNationalSociety: 'Participating National Societies',
  drefFormPartnerNationalSocietyDescription: 'Briefly set out which PNS are present and give details of PNS contributions/roles on the ground and remotely for this specific operation',
  drefFormNationalOtherActors: 'Other Actors Actions Related To The Current Event',
  drefFormInternationalAssistance: 'Government has requested international assistance',
  drefFormNationalAuthorities: 'National authorities',
  drefFormUNorOtherActors: 'UN or other actors',
  drefFormCoordinationMechanism: 'Are there major coordination mechanisms in place?',
  drefFormCoordinationMechanismDescription: 'List coordination mechanisms/platform in place at local/district and national level. Indicate the lead authorities/agencies. How the National Society is involved/positioned in this coordination. Does the NS in any lead/co-lead role? Any identified gap/overlap in the coordination (e.g., sector missing…)?',
  drefFormNeedsIdentified: 'Needs (Gaps) Identified',
  drefFormImminentNeedsIdentified: 'Anticipated Needs',
  drefFormActionFieldsLabel: 'Select the needs that apply.',
  drefFormGapsInAssessment: 'Any identified gaps/limitations in the assessment',

  drefFormEssentialInformation: 'Essential Information',
  drefFormNationalSociety: 'Name of National Society',
  drefFormForAssessment: 'Is this the DREF for assessment?',
  drefFormDisasterDetails: 'Disaster Details',
  drefFormImminentDisasterDetails: 'Hazard Details',
  drefFormDisasterTypeLabel: 'Type of Disaster',
  drefFormImminentDisasterTypeLabel: 'Type of Hazard',
  drefFormTypeOfOnsetLabel: 'Type of Onset',
  drefFormAddCountry: 'Add Country',
  drefFormAddRegion: 'Region/Province',
  drefFormRiskCountryLabel: 'At Risk Country and Region(s)',
  drefFormRiskPeopleLabel: 'Total population at risk',
  drefFormDateOfImpact: 'Forecasted Date of Impact',
  drefFormNSAnticipatoryAction: 'National Society anticipatory actions started',
  drefFormDisasterCategoryLabel: 'Disaster Category',
  drefFormImminentDisasterCategoryLabel: 'Disaster Category (Optional)',
  drefFormAffectedCountryAndProvinceImminent: 'Affected Country and Affected Region(s)',
  drefFormPeopleAffected: 'Total affected population',
  drefFormPeopleAffectedDescriptionImminent: 'Includes all those whose lives and livelihoods are at risk as a direct result of the shock or stress.',
  drefFormPeopleAffectedDescriptionSlowSudden: 'People Affected include all those whose lives and livelihoods have been impacted as a direct result of the shock or stress.',
  drefFormPeopleTargeted: 'Number of people targeted',
  drefFormPeopleTargetedDescription: 'Include all those whose the National Society is aiming or planning to assist',
  drefFormRequestAmount: 'Requested Amount in CHF',
  drefFormEmergencyAppealPlanned: 'Emergency appeal planned',
  drefFormUploadMap: 'Upload map',
  drefFormUploadMapDescription: 'Add a map highlighting the targeted areas for this operation, it will be used for the publicly published DREF application.',
  drefFormUploadCoverImage: 'Cover image',
  drefFormUploadCoverImageDescription: 'Upload a image for the cover page of the publicly published DREF application.',
  drefFormTimeFrames: 'Timeframes',
  drefFormEventDate: 'Date of the Event',
  drefFormSlowEventDate: 'Date when the trigger was met',
  drefFormGoFieldReportDate: 'Date of GO field report',
  drefFormNsResponseStarted: 'Start date of National Society actions',
  drefFormApproximateDateOfImpact: 'Approximate date of impact',
  drefFormOperationalTimeframes: 'Operational Timeframes',
  drefFormPeopleInNeed: 'People in need (Optional)',
  drefFormPeopleInNeedDescriptionImminent: 'Include all those whose physical security, basic rights, dignity, living conditions or livelihoods are threatened or have been disrupted, and whose current level of access to basic services, goods and social protection will be inadequate to re-establish normal living conditions without additional assistance',
  drefFormPeopleInNeedDescriptionSlowSudden: 'People in Need (PIN) are those members whose physical security, basic rights, dignity, living conditions or livelihoods are threatened or have been disrupted, and whose current level of access to basic services, goods and social protection is inadequate to re-establish normal living conditions without additional assistance.',
  drefFormEstimatedPeopleInNeed: 'Estimated people in need (Optional)',
  drefFormDidNationalSocietyStartedImminent: 'Did the National Society started any anticipatory actions?',
  drefFormDidNationalSocietyStartedSlow: 'Has the National Society started any actions?',

  drefFormEventDetailsTitle: 'Import data from existing field report',
  drefFormEventDescription: 'These field reports have already been filtered by the National Society that you have selected. Selecting a field report will pre-fill matching fields in this request, which you can modify.',
  drefFormPreviousOperations: 'Previous Operations',
  drefFormAffectSameArea: 'Has a similar event affected the same area(s) in the last 3 years?',
  drefFormAffectedthePopulationTitle: 'Did it affect the same population groups?',
  drefFormNsRespond: 'Did the National Society respond?',
  drefFormNsRequestFund: 'Did the National Society request funding from DREF for that event(s)?',
  drefFormNsFundingDetail: 'If yes, please specify which operations',
  drefFormNsFundingDetailDescription: ' Enter MDR code and year. Example: MDRXXX YEAR, MDRXXX YEAR',
  drefFormRecurrentText: 'If you have answered yes to all questions above, justify why the use of DREF for a recurrent event, or how this event should not be considered recurrent',
  drefFormLessonsLearnedTitle: 'Lessons learned',
  drefFormLessonsLearnedDescription: 'Specify how the lessons learnt from these previous operations are being used to mitigate similar challenges in the current operation',
  drefFormDescriptionEvent: 'Description of the Event',
  drefFormUploadSupportingDocumentButtonLabel: 'Upload document',
  drefFormUploadSupportingDocument: 'Upload any supporting documentation if relevant (Optional)',
  drefFormUploadSupportingDocumentDescription: 'Here the National Society can upload documentation that substantiates their decision to launch this operation now. For example: seasonal outlooks, forecast information, reports from credible sources...etc.',

  drefFormImminentDisaster: 'Provide any updates in the situation since the field report and explain what is expected to happen.',
  drefFormTargetCommunities: 'Explain why your National Society is acting now and what criteria is used to launch this operation.',
  drefFormTargetCommunitiesDescription: 'If the operation uses triggers related to different phases (such as readiness activities and early actions) add your triggers and data sources',
  drefFormSelectionCriteriaRisk: 'What selection criteria has been used to target people at risk?',
  drefFormTargetedActions: 'Number of persons targeted with early action',
  drefFormWhatWhereWhen: 'What happened, where and when?',
  drefFormScopeAndScaleEvent: 'Scope and scale of the event',
  drefFormScopeAndScaleDescription: 'Describe the extent this hazard will produce negative impacts on lives, livelihoods, well-being and infrastructure. Explain which people are most likely to experience the impacts of this hazard? Where do they live, and why are they vulnerable? Please explain which groups (e.g elderly, children, people with disabilities, IDPs, Refugees, etc.) are most likely to be affected? Provide historic information on how communities have been affected by the magnitude of this hazard in the past?',
  drefFormUploadPhotos: 'Upload photos (e.g. impact of the events, NS in the field, assessments)',
  drefFormUploadPhotosLimitation: 'Add maximum 2 photos',
  drefFormTargetingStrategy: 'Targeting Strategy',
  drefFormPeopleAssistedThroughOperation: 'Who will be targeted through this operation?',
  drefFormPeopleAssistedThroughOperationDescription: 'Explain the logic behind our targets. Which groups are we targeting and why are we targeting these particular groups? Explain how you will target vulnerable groups (e.g., Migrants, refugees, etc.)',
  drefFormSelectionCriteria: 'Explain the selection criteria for the targeted population',
  drefFormSelectionCriteriaDescription: 'Explain the rational and logic behind which groups are being targeted and why and address vulnerable groups',
  drefFormAssistedPopulation: 'Total Targeted Population',
  drefFormWomen: "Women",
  drefFormMen: 'Men',
  drefFormGirls: 'Girls (under 18)',
  drefFormBoys: 'Boys (under 18)',
  drefFormTotal: 'Total Population',
  drefFormTargetedPopulation: 'Targeted Population',
  drefFormEstimateResponse: 'Estimate',
  drefFormEstimatePeopleDisability: 'Estimated Percentage People with Disability',
  drefFormEstimatedPercentage: 'Estimated Percentage (Urban to Rural)',
  drefFormEstimatedUrban: 'Urban',
  drefFormEstimatedLocal: 'Rural',
  drefFormEstimatedDisplacedPeople: 'Estimated Number of People on the move (if any)',
  drefFormPeopleTargetedWithEarlyActions: 'Numbers of persons targeted with early actions (if any)',
  drefFormObjectiveAndStrategy: 'Objective and Strategy Rationale',
  drefFormObjectiveOperation: 'Overall objective of the operation',
  drefFormObjectiveOperationPlaceholder: 'This DREF allocation aims at supporting ….. of people in need affected by ……. Disaster, by providing …..(list sectors) support in the ……(list areas/regions) for …. months',
  drefFormResponseRationale: 'Operation strategy rationale',
  drefFormResponseRationaleDescription: 'Please describe the strategy to conduct the assessment exercise, main objectives, who will be involved?',
  drefFormResponseRationalePlaceholder: 'To address the needs of the targeted population, this DREF will aim at (please briefly describe the planned activities).',
  drefFormHumanResourceDescription: 'How many staff and volunteers will be involved in this operation. Briefly describe their role.',
  drefFormSurgePersonnelDeployed: 'Will surge personnel be deployed?',
  drefFormSurgePersonnelDeployedDescription: 'Please provide the role profile needed.',
  drefFormLogisticCapacityOfNs: 'If there is procurement, will it be done by National Society or IFRC?',
  drefFormLogisticCapacityOfNsDescription: 'Will it be for replenishment or for distribution? If for distribution, how long is the tendering expected to take? For Cash and Voucher Assistance, what is the status of the Financial Service Provider?',
  drefFormSafetyConcerns: 'Any potential risk to the implementation of this operation?',
  drefFormSafetyConcernsDescription: 'What will be the mitigation measures? Any safety and security concerns? How will the National Society ensure the safety of the staff, volunteers and community?',
  drefFormPmer: 'How will this operation be monitored?',
  drefFormPmerDescription: 'Will there be IFRC monitoring visits? How will it be deployed?',
  drefFormCommunication: 'Please briefly explain the National Societies communication strategy for this operation.',
  drefFormCommunicationDescripiton: 'Will the IFRC be supporting with communication? What roles will be involved?',
  drefFormPlannedIntervention: 'Planned Intervention',
  drefFormInterventionsLabel: 'Select the interventions that apply.',
  drefFormSupportServices: 'About Support Services',
  drefFormRiskSecurityAddButton: 'Add New Risk',
  drefFormRiskSecurityRiskLabel: 'Risk',
  drefFormRiskSecurityMitigationLabel: 'Mitigation action',
  drefFormRiskSecurity: 'Risk and security considerations',
  drefFormRiskSecurityPotentialRisk: 'Please indicate about potential operational risk for this operations and mitigation actions',
  drefFormRiskSecurityPotentialRiskDescription: 'Please consider any possible challenges to conduct the assessment, any possible limitations in getting the information required and overall risk to the implementation',
  drefFormRiskSecuritySafetyConcern: 'Please indicate any security and safety concerns for this operation',
  drefOperationalUpdateExportButton: 'Export',
  drefOperationalUpdateSaveButton: 'Save',

  drefTableInProgressHeading: 'In-progress applications',
  drefTablePublishedHeading: 'Published applications',
  drefOperationalUpdateNewLabel: 'New Operational Update',
  drefOperationalUpdateEditLastLabel: 'Edit last Operational Update',
  drefOperationalUpdateViewAllLabel: 'View all Operational Update',
  drefFetchingErrorMessage: 'there was an error fetchig the Dref application list',
  drefOperationalUpdateSuccessMessage: 'Operational update created/updated successfully',
  drefOperationalUpdateFailureMessage: 'Failed to create/load Operational update',
  drefPublishConfirmationMessage: 'Are you sure you want to publish the DREF?',
  drefOperationalUpdatePublishConfirmationMessage: 'Are you sure you want to publish the DREF Operational Update?',
  drefOperationalUpdatePublishConfirmationFailureMessage: 'Failed to publish the Operational Update',
  drefPublishButtonLabel: 'Publish',
  drefOperationalUpdateSaveButtonLabel: 'Save',
  drefOperationalUpdateButtonLabel: 'update',
  drefOperationalUpdateTitle: 'Operational Updates',
  drefOperationalUpdatePageTitle: 'IFRC GO - DREF operational update',
  drefOperationalUpdatePageHeading: 'DREF Operational Update Application',
  drefOperationalUpdateOverviewLabel: 'Operation Overview',
  drefOperationalUpdateEventDetailsLabel: 'Event Details',
  drefOperationalUpdateNeedsLabel: 'Actions/Needs',
  drefOperationalUpdateOperationLabel: 'Operation',
  drefOperationalUpdateSubmissionLabel: 'Submission',
  drefOperationalUpdateAllocationSoFar: 'Budget Allocated So far',
  drefOperationalUpdateAdditionalAllocationRequested: 'Additional Allocation Requested',
  drefOperationalUpdateTotalAllocation: 'Total DREF Allocation',
  drefOperationalUpdateNumber: 'Operational Update Number',
  drerfOperationalUpdateCoverImageLabel: 'Cover image',
  drefOperationalUpdateTimeFrameDateOfEvent: 'Operation start Date',
  drefOperationalUpdateTimeFrameReportingTimeFrame: 'Reporting timeframe',
  drefOperationalUpdateTimeFrameReportingTimeFrameStart: 'Reporting Timeframe start date',
  drefOperationalUpdateTimeFrameReportingTimeFrameEnd: 'Reporting Timeframe end date',
  drefOperationalUpdateTimeFrameExtensionRequested: 'Is timeframe extension requested?',
  drefOperationalUpdateTimeFrameExtensionRequestedIfYes: 'New operational end date',
  drefOperationalUpdateTimeFrameTotalOperatingTimeFrame: 'Total operating timeframe',
  drefOperationalUpdateTimeFrameDateOfApproval: 'Date of approval',
  drefOperationalUpdateSummaryChangeHeading: 'Summary of changes',
  drefOperationalUpdateSummaryAreYouChangingTimeFrame: 'Are you changing the timeframe of the operation',
  drefOperationalUpdateSummaryAreYouChangingStrategy: 'Are you changing the operational strategy',
  drefOperationalUpdateSummaryAreYouChangingTargetPopulation: 'Are you changing the target population of the operation',
  drefOperationalUpdateSummaryAreYouChangingGeographicalLocation: 'Are you changing the geographical location',
  drefOperationalUpdateSummaryAreYouChangingBudget: 'Are you making changes to the budget',
  drefOperationalUpdateSummaryRequestForSecondAllocation: 'Is this a request for a second allocation',
  drefOperationalUpdateSummaryExplain: 'Please explain the summary of changes and justification',
  drefOperationalUpdateEventMaterialize: 'Has the forecasted event materialize?',
  drefOperationalUpdateEventMaterializeExplain: 'Please explain how is the operation is transitioning from Anticipatory to Response',
  drefOperationalUpdateEventMaterializeExplainDescription: 'Explain on whether the specified triggers have been met, and if the event has materialized either as forecasted or if there were any differences. Also please provide an update on the readiness, prepositioning and/or early actions implemented so far',
  drefOperationalUpdateEventOccur: 'Has the event occurred?',
  drefOperationalUpdateDescriptionOfEventHeading: 'Description of the event',
  drefOperationalUpdateDescriptionOfEventLabel: 'Has anything changed in the context since the request',
  drefOperationalUpdateMovementPartners: 'Movement Partners',
  drefOperationalUpdatePlannedIntervention: 'Update on Intervention',
  drefOperationalUpdateProgressTowardsOutcome: 'Progress Towards Outcome',
  drefOperationalUpdateIndicatorActualLabel: 'Actual',
  drefOperationalUpdateIndicatorMaleLabel: 'Male',
  drefOperationalUpdateIndicatorFemaleLabel: 'Female',

  operationalUpdateExportTitle: 'operational update',
  operationalUpdateExportPeopleAffected: 'People affected:',
  operationalUpdateExportPeopleTargeted: 'People targeted:',
  operationalUpdateExportNewOperationalEndDate: 'New Operational end date:',
  operationalUpdateExportPersonReachedLabel: 'Persons reached:',
  operationalUpdateCurrentNsImageLabel: 'Add photos of National Society Operation',
  drefOperationalUpdateExportTimeFrameTotalOperatingTimeFrame: 'Total operating timeframe:',

  finalReportTitle: 'Final Report',
  finalReportPageTitle: 'IFRC GO - DREF Final Report Application',
  finalReportPageHeading: 'DREF Final Report',
  finalReportTabOperationOverview: 'Operation Overview',
  finalReportTabEventDetails: 'Event Details',
  finalReportTabNeeds: 'Actions/Needs',
  finalReportTabOperationReport: 'Operation Report',
  finalReportTabSubmission: 'Submission',

  finalReportCreateButtonLabel: 'Create Final Report',
  finalReportEditButtonLabel: 'Edit Final Report',
  finalReportPublishButtonLabel: 'Publish Final Report',

  finalReportOperationOverviewTitle: 'operation overview',
  finalReportEssentialInformationTitle: 'Essential Information',
  finalReportEssentialTitle: 'DREF Title',
  finalReportEssentialDescription: 'Add country, type of disaster and location to the title',

  finalReportNationalSociety: 'Name of National Society',
  finalReportDisasterDetails: 'Disaster Details',
  finalReportDisasterTypeLabel: 'Type of Disaster',
  finalReportTypeOfOnsetLabel: 'Type of Onset',
  finalReportDisasterCategoryLabel: 'Disaster Category',
  finalReportImminentDisasterDetails: 'Hazard Details',
  finalReportImminentDisasterTypeLabel: 'Type of Hazard',
  finalReportAffectedCountryAndProvinceImminent: 'Affected Country and Affected Region(s)',
  finalReportRiskCountryLabel: 'At Risk Country and Region(s)',
  finalReportAddCountryLabel: 'Add Country',
  finalReportAddRegion: 'Region/Province',
  finalReportPeopleAffected: 'People Affected',
  finalReportRiskPeopleLabel: 'People at Risk',
  finalReportPeopleTargeted: 'Number of people targeted',
  finalReportPeopleAssisted: 'Number of people assisted',
  finalReportTotalAllocation: 'Total DREF Allocation',
  finalReportTimeFrame: 'timeframes',
  finalReportDateOfPublication: 'Publication date of final report',
  finalReportTotalOperatingTimeFrame: 'Total operating timeframe',
  finalReportStartOfOperation: 'Start of operation',
  finalReportEndOfOperation: 'Operational end date',

  finalReportDescriptionOfEvent: 'Description of the Event',
  finalReportUploadMap: 'Upload map',
  finalReportUploadPhotos: 'Upload Photos of the implementation',
  finalReportWhatWhereWhen: 'What happened, where and when?',
  finalReportScopeAndScaleEvent: 'Scope and scale of the event',
  finalReportImminentDisaster: 'For imminent disaster, explain what is expected to happen, where, when and how is above average ?',
  finalReportImmientDisaster: 'For imminent disaster, explain what is expected to happen, where, when and how is above average ?',
  finalReportScopeAndScaleDescription: 'Describe the extent this hazard will produce negative impacts on lives, livelihoods, well-being and infrastructure. Explain which people are most likely to experience the impacts of this hazard? Where do they live, and why are they vulnerable? Please explain which groups (e.g elderly, children, people with disabilities, IDPs, Refugees, etc.) are most likely to be affected? Provide historic information on how communities have been affected by the magnitude of this hazard in the past?',

  finalReportHaveNationalSocietyConducted: 'Have the National Society conducted any intervention additionally to those part of this DREF Operation?',
  finalReportDescriptionOfAdditionalActivities: 'Please provide a brief description of those additional activities',
  finalReportNationalSocietiesActions: 'National Society Actions',
  finalReportMovementPartners: 'Movement Partners Actions',
  finalReportIfrc: 'IFRC',
  finalReportIcrc: 'ICRC',
  finalReportPartnerNationalSociety: 'Participating National Societies',
  finalReportNationalOtherActors: 'Other Actors Actions Related To The Current Event ',
  finalReportInternationalAssistance: 'Government has requested international assistance',
  finalReportNationalAuthorities: 'National authorities',
  finalReportUNorOtherActors: 'UN or other actors',
  finalReportCoordinationMechanism: 'Are there major coordination mechanisms in place?',
  finalReportCoordinationMechanismDescription: 'List coordination mechanisms/platform in place at local/district and national level. Indicate the lead authorities/agencies. How the National Society is involved/positioned in this coordination. Does the NS in any lead/co-lead role? Any identified gap/overlap in the coordination (e.g., sector missing…)?',
  finalReportNeedsTabTitle: 'needs',
  finalReportNeedsIdentified: 'Needs',
  finalReportImminentNeedsGapsIdentified: 'Anticipated Needs',
  finalReportActionFieldsLabel: 'Select the needs that apply.',

  finalReportTargetingStrategy: 'Targeting Strategy',
  finalReportPeopleAssistedThroughOperation: 'Who will be targeted through this operation?',
  finalReportSelectionCriteria: 'Explain the selection criteria for the targeted population',
  finalReportChangeToOperationStrategy: 'Has there been any changes to the operation strategy',
  finalReportChangeToOperationStrategyExplain: 'Explain',
  finalReportTargetedPopulation: 'Target Population',
  finalReportWomen: 'Women',
  finalReportGirls: 'Girls (under 18)',
  finalReportMen: 'Men',
  finalReportBoys: 'Boys (under 18)',
  finalReportEstimatePeopleDisability: 'Estimated Percentage People with Disability',
  finalReportEstimatedPercentage: 'Estimated Percentage (Urban to Rural)',
  finalReportEstimatedUrban: 'Urban',
  finalReportEstimatedLocal: 'Rural',
  finalReportEstimatedDisplacedPeople: 'Estimated Number of Displaced People (if any)',
  finalReportPeopleTargetedWithEarlyActions: 'Numbers of persons targeted with early actions',
  finalReportObjectiveAndStrategy: 'Objective and Strategy Rationale',
  finalReportObjectiveOperation: 'Overall objective of the operation',
  finalReportResponseStrategyImplementation: 'Response strategy implementation',
  finalReportImplementation: 'Implementation',
  finalReportSelectIntervention: 'Select the interventions that apply.',
  finalReportSupportServices: 'About Support Services',
  finalReportFederationWideAndPartners: 'Federation Wide and Partners',
  finalReportWantToReport: 'Want to report of activities outside of the operational strategy of this DREF?',
  finalReportAdditionalNationalSocietyAction: 'Additional National Society Actions',
  finalReportEstimateResponse: 'Estimate',
  finalReportPlannedInterventionChallenges: 'Challenges',
  finalReportPlannedInterventionLessonsLearnt: 'Lessons Learnt',
  finalReportPlannedInterventionNarrativeAchievement: 'Narrative description of achievements ',
  finalReportFinancialReport: 'Financial report',
  finalReportFinancialReportAttachment: 'Please attach the final financial report',
  finalReportFinancialReportVariances: 'Please explain variances (if any)',

  finalReportTrackingData: 'tracking data',
  finalReportAppealCode: 'MDR Code',
  finalReportGlideNum: 'GLIDE number',
  finalReportAppealManager: 'IFRC Appeal Manager:',
  finalReportProjectManager: 'IFRC Project Manager',
  finalReportNationalSocietyContact: 'National Society contact:',
  finalReportIfrcEmergency: 'IFRC focal point for the emergency',
  finalReportMediaContact: 'Media Contact',

  finalReportSuccessMessage: 'Final Report created successfully',
  finalReportFailureMessage: 'Failed to create/load Final Report',
  finalReportErrorDescription: 'There is an error loading Dref Final Report',
  finalReportPublishConfirmationMessage: 'Are you sure you want to publish the DREF Final Report?',
  finalReportPublishConfirmationFailureMessage: 'Failed to publish the Final Report',

  finalReportExportTitle: 'Final Report',
  finalReportExportAppealNum: 'Appeal no:',
  finalReportExportGlideNum: 'Glide no:',
  finalReportExportTotalAllocation: 'Total DREF Allocation:',
  finalReportExportPeopleAffected: ' People affected:',
  finalReportExportPeopleTargeted: 'People targeted:',
  finalReportExportDateOfPublication: 'Date of publication:',
  finalReportExportStartOfOperation: 'Start of operation:',
  finalReportExportTotalOperatingTimeFrame: 'Total operating timeframe:',
  finalReportExportAffectedArea: 'Affected areas:',
  finalReportExportTotalPopulation: 'Total Population',
  finalReportBudgetOverview: 'Budget Overview',
  FinalReportExportContactInformation: 'Contact Information',
  finalReportExportContactDescription: 'For further information, specifically related to this operation please contact:',
  finalReportExportNationalSocietyContact: 'National Society contact:',
  finalReportExportAppealManager: 'IFRC Appeal Manager:',
  finalReportExportProjectManager: 'IFRC Project Manager:',
  finalReportExportIfrcEmergency: 'IFRC focal point for the emergency:',
  finalReportExportMediaContact: 'Media Contact:',
  finalReportExportReference: 'Click here for the reference',
  finalReportPhotosOfImplementation: 'Photos of the implementation',

  finalReportExportPersonReachedLabel: 'Persons reached:',
  finalReportIndicatorTargetLabel: 'Target',
  finalReportIndicatorMaleLabel: 'Male',
  finalReportIndicatorFemaleLabel: 'Female',
  finalReportIndicatorActualLabel: 'Actual',
  finalReportExportIndicators: 'Indicators',
  finalReportExport: 'Final Report Export',
};

export type DrefStrings = typeof dref;

export default dref;
