const emergency = {
  emergenciesTableError: 'Latest emergencies not available.',
  emergenciesTableDate: 'Start Date',
  emergenciesTableName: 'Name',
  emergenciesTableDisasterType: 'Disaster Type',
  emergenciesTableGlide: 'Glide',
  emergenciesTableRequestedAmt: 'Requested Amount',
  emergenciesTableAffected: '# Affected',
  emergenciesTableCountry: 'Countries',
  emergenciesTableViewAll: 'View all emergencies',
  emergenciesTableRecentEmergencies: 'Recent Emergencies',
  emergenciesRecentViewAll: 'View All Emergencies For',
  emergenciesMapHeading: 'Emergencies by Country',
  emergenciesMapDownloadTitle: 'Emergencies',
  emergenciesMapWithoutIFRC: 'Without IFRC response*',
  emergenciesMapWithIFRC: 'With IFRC response',
  emergenciesMapMixResponse: 'Mixed Level of response',
  emergenciesMapDescription: '*IFRC response indicates the existence of appeal(s) and/or DREF(s) for a given emergency.',
  emergenciesMapPopoverDismiss: 'Dismiss',
  emergenciesMapPopoverPeopleAffected: '{numAffected} People Affected',
  emergenciesMapPopoverTotalEmergencies: '{totalEmergencies} Emergencies',
  emergenciesMapPopoverWithoutIFRC: '{withoutResponse} without IFRC response',
  emergenciesMapPopoverWithIFRC: '{withResponse} with IFRC response',
  emergencyMapExport: 'Export',
  emergencyMapSelected: 'selected',
  emergencyMapAffectedCountry: 'Affected country',
  emergencyMapAffectedRegion: 'Affected provinces',
  emergencyMapBorder: 'border',
  emergencyMapBorderDisputed: 'Disputed borders',
  emergencyMapTerritory: 'territory',
  emergencyMapDisputedTerritory: 'Disputed territory',
  emergenciesDashHeading: 'Emergencies by Type',
  emergenciesDashDate: 'Date',
  emergenciesDashTotal: 'Total',
  emergenciesDashOverLastYear: 'Emergencies Over the Last Year',
  emergenciesDashLast30Days: 'Emergencies in the last 30 days',
  emergenciesDashOverTime: 'DREFS and Appeals over time',
  emergencyPageTitleStatic: 'IFRC GO - Emergency',
  // not used -   emergencyPageLabel: 'Emergency',
  emergencyPageTitle: 'IFRC GO - {name}',
  emergencyTabDetails: 'Emergency Details',
  emergencyTabReports: 'Reports/Documents',
  emergencyTabSurge: 'Surge',
  emergencyKeyFiguresTitle: 'Key Figures',
  emergencyOverviewTitle: 'Overview',
  emergencyOverviewBoxTitle: 'Emergency Overview',
  emergencyDisasterType: 'Disaster Type',
  emergencyDisasterCat: 'Disaster Categorization',
  emergencyGovtReqIntlAsst: 'Government Requests International Assistance',
  emergencyNSReqIntlAsst: 'NS Requests International Assistance',
  // not used -   emergencyDREF: 'DREF',
  // not used -   emergencyRapidResponsePersonnel: 'Rapid Response Personnel',
  emergencyAffectedRegions: 'Affected Provinces',
  emergencySituationalOverviewTitle: 'Situational Overview',
  emergencyLinksTitle: 'Links',
  emergencyFeaturedDocumentsTitle: 'Featured Documents',
  emergencyAlertsTitle: 'Open Surge Alerts',
  emergencyPersonnelTitle: 'Personnel',
  emergencyERUTitle: 'ERUs',
  emergencyFieldReportsTitle: 'Field Reports',
  emergencyFieldReportsWithCountTitle: 'Reports ({count})',
  emergencyAppealDocumentsTitle: 'Appeal Documents',
  emergencyAppealDocHeaderDate: 'Date',
  emergencyAppealDocHeaderCode: 'Code',
  emergencyAppealDocHeaderName: 'Name',
  emergencyResponseDocumentsTitle: 'Response Documents',
  emergencyReportSearchPlaceholder: 'Search',
  emergencyDocumentsNoResultsMessage: 'No results found for search',
  emergencyContactsIFRC: 'IFRC',
  emergencyContactsNS: 'National Societies',
  emergencyContactsTitle: 'Contacts',
  emergencyContactTitle: 'Contact',
  emergencyContactEmptyMessage: 'No current contacts',
  emergencyContactsTableHeaderName: 'Name',
  emergencyContactsTableHeaderTitle: 'Title',
  emergencyContactsTableHeaderType: 'Type',
  emergencyContactsTableHeaderContact: 'Contact',
  emergencyFieldReportTableHeaderDate: 'Date',
  emergencyFieldReportTableHeaderName: 'Name',
  emergencyFieldReportTableHeaderCountries: 'Countries',
  emergencyFieldReportTableHeaderRegions: 'Regions',
  emergencyFieldReportLinkTitle: 'View Field Report',
  emergencyTopOverviewSectionTitle: 'Emergency Overview',
  emergencyPotentiallyAffectedLabel: 'Potentially Affected',
  emergencyHighestRiskLabel: 'Highest Risk',
  emergencyAffectedPopulationCentresLabel: 'Affected Population Centres',
  emergencyAssistedByGovernmentLabel: 'Number of People Assisted by Government - Early Action',
  emergencyAssistedByRCRCLabel: 'Number of People Assisted by RCRC Movement - Early Action',
  emergencyCasesLabel: 'Cases',
  emergencySuspectedCasesLabel: 'Suspected Cases',
  emergencyProbableCasesLabel: 'Probable Cases',
  emergencyConfirmedCasesLabel: 'ConfirmedCases',
  emergencyDeadLabel: 'Dead',
  emergencyAffectedLabel: 'Affected',
  emergencyInjuredLabel: 'Injured',
  emergencyMissingLabel: 'Missing',
  emergencyDisplacedLabel: 'Displaced',
  emergencyAssistedLabel: 'Assisted',
  emergencyLocalStaffLabel: 'Local staff',
  emergencyVolunteersLabel: 'Volunteers',
  emergencyDelegatesLabel: 'Delegates',
  emergencyPeopleTargetedLabel: 'People Targeted',
  emergencyFundingRequirementsLabel: 'Funding Requirements (CHF)',
  emergencyFundingLabel: 'Funding (CHF)',
  emergencyNoDocumentsMessage: 'No documents added',
  emergencySourceFigure: 'Source: {source}',
  emergencyActionSubscribeLabel: 'Follow',
  emergencyActionUnsubscribeLabel: 'Unfollow',
  emergencyActionEditEventLabel: 'Edit Event',
  emergencyActionCreateThreeWActivityLabel: 'Create 3W Activity',
  emergencyResponseDocumentSearchEmptyMessage: 'No document found for the given search',
  emergencyAddReportButtonLabel: 'Add a Report',
  emergenciesTitle: 'IFRC GO - Emergencies',
  emergenciesTableTitle: 'Emergencies in the last 30 days',
};

export type EmergencyStrings = typeof emergency;

export default emergency;
