const flashUpdate = {
    flashUpdateFormPageTitle: 'IFRC GO - Flash Update Request',
    flashUpdateFormPageDescription: 'The following information is provided for early warning and rapid dissemination and is based upon initial information only. IFRC will obtain more accurate and detailed information as more is known about the event.',
    flashUpdateFormExportLabel: 'Export',
    flashUpdateFormSaveButtonLabel: 'Save',
    flashUpdateFormPageHeading: 'Flash Update',
    flashUpdateTabContextLabel: 'Context',
    flashUpdateTabActionLabel: 'Actions',
    flashUpdateTabFocalLabel: 'Focal Points',
    flashUpdateFormFieldGeneralError: 'Please correct all the errors!',
    flashUpdateContinueButtonLabel: 'Continue',
    flashUpdateBackButtonLabel: 'Back',
    flashUpdateSaveButtonLabel: 'Save',
    flashUpdateSubmitButtonLabel: 'Submit',
    flashUpdateFormContextHeading: 'Context',
    flashUpdateFormContextCountryTitle: 'Country and Province/Region *',
    flashUpdateFormContextCountryLabel: 'Select a country',
    flashUpdateFormContextProvinceLabel: 'Select region / province',
    flashUpdateFormContextCountryDescription: 'Anticipated country or several countries (max 10).',
    flashUpdateFormContextCountryButton: 'Add Country',
    flashUpdateFormContextHazardTypeTitle: 'Hazard Type *',
    flashUpdateFormContextHazardTypeLabel: 'Select a hazard type',
    flashUpdateFormContextTitle: 'Title *',
    flashUpdateFormContextTitleDescription: 'The title is automatically populated based on your selection above with the date of this report. You may edit it with any required details.',
    flashUpdateFormContextTitlePlaceholder: 'e.g. Malawi - Central Region: Floods Flash Update 03/2019 ',
    flashUpdateFormContextSituationalTitle: 'Situational Overview *',
    flashUpdateFormContextSituationalDescription: 'Brief overview of the current situation and the anticipated disaster.',
    flashUpdateFormContextSituationalPlaceholder: 'Description of the situation',
    flashUpdateFormContextGraphicTitle: 'Graphic',
    flashUpdateFormContextGraphicDescription: 'Upload any supportive graphics',
    flashUpdateFormContextMapTitle: 'Map',
    flashUpdateFormContextMapDescription: 'Upload any supportive maps',
    flashUpdateFormContextReferenceTitle: 'References',
    flashUpdateFormContextReferenceDescription: 'Upload any supportive links or documents',
    flashUpdateFormContextReferenceDateLabel: 'Date',
    flashUpdateFormContextReferenceNameLabel: 'Name or Source Description',
    flashUpdateFormContextReferenceUrlLabel: 'Add URL',
    flashUpdateFormContextReferenceUrlDragLabel: 'Drag & Drop Files Here',
    flashUpdateFormContextReferenceUrlOrLabel: 'or',
    flashUpdateFormContextReferenceUrlButtonLabel: 'Upload',
    flashUpdateFormContextReferenceAddButtonLabel: 'Add Reference',
    flashUpdateFormContextReferenceUrlPlaceholder: 'No document selected',
    flashUpdateFormActionTakenTitle: 'Actions',
    flashUpdateFormActionTakenByNationalSocietyLabel: 'Actions Taken by National Society',
    flashUpdateFormActionTakenByNationalSocietyDescription: 'Select the activities undertaken by the National Society and describe.',
    flashUpdateFormActionTakenByNationalSocietyPlaceholder: 'Brief description of the action',
    flashUpdateFormActionTakenByIfrcLabel: 'Actions Taken by IFRC',
    flashUpdateFormActionTakenByIfrcDescription: 'Select the activities taken or coordination done by the IFRC and describe.',
    flashUpdateFormActionTakenByIfrcPlaceholder: 'Brief description of the action',
    flashUpdateFormActionTakenByRcrcLabel: 'Actions Taken by RCRC',
    flashUpdateFormActionTakenByRcrcDescription: 'Select the activities taken or coordination done by the RCRC and describe.',
    flashUpdateFormActionTakenByRcrcPlaceholder: 'Brief description of the action',
    flashUpdateFormActionTakenByGovernmentLabel: 'Actions Taken by Government',
    flashUpdateFormActionTakenByGovernmentDescription: 'Select the activities undertaken by the government and describe.',
    flashUpdateFormActionTakenByGovernmentPlaceholder: 'Brief description of the action',
    flashUpdateFormFocalOriginatorTitle: 'Originator',
    flashUpdateFormFocalOriginatorDescription: 'IFRC staff completing the Flash Update',
    flashUpdateFormFocalOriginatorNameLabel: 'Name *',
    flashUpdateFormFocalOriginatorTitleLabel: 'Title',
    flashUpdateFormFocalOriginatorEmailLabel: 'Email *',
    flashUpdateFormFocalOriginatorPhoneLabel: 'Phone',
    flashUpdateFormFocalIfrcTitle: 'IFRC Focal Point',
    flashUpdateFormFocalIfrcDescription: 'IFRC staff who is overall responsible for supporting the NS in its response to the disaster event.',
    flashUpdateFormFocalIfrcNameLabel: 'Name',
    flashUpdateFormFocalIfrcTitleLabel: 'Title',
    flashUpdateFormFocalIfrcEmailLabel: 'Email',
    flashUpdateFormFocalIfrcPhoneLabel: 'Phone',
    flashUpdateFormVisibilityTitle: 'Visibility',
    flashUpdateFormVisibilityDescription: 'After hitting Submit, the information will be shared with IFRC Secretariat only.',
    flashUpdateFormFocalIfrcSecretariatLabel: 'IFRC Secretariat',
    flashUpdateFormFocalIfrcRcrcNetworkLabel: 'IFRC Network',
    flashUpdateFormFocalIfrcRcrcNetworkAndDonorsLabel: 'IFRC Network and Donors',
    flashUpdateReportsTableTitle: 'Latest Flash Updates',
    flashUpdateReportsTableViewAllReports: 'View All Flash Updates',
    flashUpdateReportsTableViewAllReportsTitle: 'All Flash Updates',
    flashUpdateReportsTableViewAllReportsBreadcrumbTitle: 'Flash Updates',
    flashUpdateAllFlashUpdatePageHeading: 'All Flash Updates',
    flashUpdateIfrcSecretariatLabel: 'IFRC Secretariat',
    flashUpdateRcrcNetworkLabel: 'RCRC Network',
    flashUpdateRcrcNetworkAndDonorsLabel: 'RCRC Network and Donors',
    flashUpdateNumber: 'Flash Update #{number}',
    flashUpdateActionTakenTitle: 'ACTIONS TAKEN',
    flashUpdateSituationalOverviewTitle: 'SITAUTIONAL OVERVIEWS',
    flashUpdateMapTitle: 'MAPS',
    flashUpdateImageTitle: 'Images',
    flashUpdateDescriptionTitle: 'Description',
    flashUpdateActionsTitle: 'Actions',
    flashUpdateResourcesTitle: 'Resources',
    flashUpdateFormRedirectMessage: 'Flash report updated, redirecting...',
    flashUpdateFormSaveRequestSuccessMessage: 'Flash Update Application created/updated successfully',
    flashUpdateFormSaveRequestFailureMessage: 'Failed to create/update Flash Update Application',
    flashUpdateFormLoadRequestFailureMessage: 'Failed to load Flash Update Application',
    flashUpdateFormLoadErrorTitle: 'Failed to load Flash Update Application',
    flashUpdateFormLoadErrorDescription: 'There was an error loading the Flash Update Application',
    flashUpdateFormLoadErrorHelpText: 'Please make sure that the application with given id exists and you have the permission to view it',
};

export type FlashUpdateStrings = typeof flashUpdate;

export default flashUpdate;
