const register = {
    registerTitle: 'IFRC GO - Register',
    registerHeading: 'Register',
    registerSubHeader: 'Staff, members and volunteers of the Red Cross Red Crescent Movement (National Societies, the IFRC and the ICRC) are welcome to register for a user account on GO, to access information for the Membership. Other responders and members of the public may browse the public areas of the site without registering for an account.',
    registerFirstName: 'First Name *',
    registerLastName: 'Last Name *',
    registerEmail: 'Email *',
    // not used -   registerUsername: 'Username *',
    // not used -   registerUsernameInfo: 'This will be your username to log into the platform',
    registerCountry: 'Country *',
    registerCity: 'City *',
    registerOrganizationType: 'Organization Type *',
    registerOrganizationName: 'Organization Name *',
    registerOfficeName: 'Office Name *',
    registerDepartment: 'Department',
    registerPosition: 'Position',
    registerPhoneNumber: 'Phone Number',
    registerJustificationLabel: 'Justification *',
    registerJustification: 'Please justify that you are part of RCRC Movement.',
    registerPassword: 'Password *',
    registerConfirmPassword: 'Confirm Password *',
    registerJustify: 'It appears you do not have an official Red Cross Red Crescent email, we will need to verify your status. Please note, this may take some time.',
    registerContactName: 'Contact name',
    registerContactEmail: 'Contact email',
    registerRequestAccess: 'Request Access',
    registerSubmit: 'Register',
    registerSubmitError: 'There are errors in the form. Please correct them before submitting again.',
    registerAccountPresent: 'Already have an account?',
    registerGotoLogin: 'Go to login page',
    registerLogin: 'Login',
};

export type RegisterStrings = typeof register;

export default register;
