const threeW = {
  globalThreeWPageTitle: 'IFRC GO - Global 3W Response',
  globalThreeWPageHeading: 'Global 3W Response',
  globalThreeWPageDescriptionP1: 'The \'Who does What, Where\' or 3w aims to map the global footprint of the Red Cross Red Crescent Movement. It is a global database of projects conducted by National Societies, IFRC and the ICRC, broken down by sector, location, budget and people targeted and reached.',
  globalThreeWPageDescriptionP2: 'Find explanatory videos and guidance on the Resources page. Please note data is incomplete and maintained by GO users. If you know of an error or omission, please submit data or contact {contactLink} for assistance.',
  globalThreeWAddProjectButtonLabel: 'Add 3W Project',
  globalThreeWExploreRegionalButtonLabel: 'Explore Regional 3W',
  globalThreeWKeyFigureOngoingProjectsTitle: 'Ongoing Projects',
  globalThreeWKeyFigureActiveNSTitle: 'Active National Societies',
  globalThreeWKeyTargetedPopulationTitle: 'Targeted Population',
  globalThreeWChartProjectPerSectorTitle: 'Project Per Sector',
  globalThreeWChartProgrammeTypeTitle: 'Programme Type',
  globalThreeWChartTopTagsTitle: 'Top Tags',
  globalThreeWMapHeading: 'NS with ongoing projects',

  allThreeWPageTitle: 'IFRC GO - All 3W',
  allThreeWPageHeading: 'All 3W Projects ({count})',
  allThreeWInCountryPageHeading: 'All 3W Projects in {country} ({count})',
  allThreeWNSPageHeading: 'All 3W Projects by {ns} ({count})',

  newThreeWPageTitle: 'IFRC GO - New 3W Project',
  newThreeWPageHeading: 'Create 3W Project',
  // not used -   threeWFilterReportingNs: 'National Societies',
  // not used -   threeWFilterReportingNsPlaceholer: 'All National Societies',
  // not used -   threeWProgrammeTypePlaceholder: 'All Programme Types',
  // not used -   threeWSector: 'Sectors of Activity',
  // not used -   threeWSectorPlaceholder: 'All Sectors',
  threeWTag: 'Tag',
  // not used -   threeWTagPlaceholder: 'All Tags',
  // not used -   threeWStatusPlaceholder: 'All Status',
  threeWAdd: 'Add',
  threeWExport: 'Export',
  threeWDeleteProject: 'Delete project',
  threeWDeleteProjectMessage: 'Are you sure you want to delete the project?',
  threeWMapLastUpdate: 'Last update',
  threeWMapStatus: 'Status',
  // not used -   threeWMapSector: 'Sector',
  // not used -   threeWMapRegions: 'Regions',
  threeWMapProgrammeType: 'Programme type',
  threeWMapBudget: 'Budget',
  // not used -   threeWMapProjects: '3W Projects',
  // not used -   threeWProjectDetails: 'Red Cross / Red Crescent activities',
  threeWClose: 'Close',
  // not used -   threeWProjectName: 'Project Name',
  threeWStartDate: 'Start Date',
  threeWEndDate: 'End Date',
  // not used -   threeWProjectDistricts: 'Project Districts',
  threeWNationalSociety: 'Reporting National Society',
  threeWNationalSocietyContact1: 'NS contact name, role',
  threeWNationalSocietyContact2: 'NS contact email',
  threeWLinkedOperation: 'Linked Operation',
  threeWCountryAndRegion: 'Country and Region/Province',
  threeWBudgetAmount: 'Budget Amount (CHF)',
  threeWProgrammeType: 'Programme Type',
  threeWProgrammeTypeTooltip: 'This can be Domestic, Bilateral, Multilateral. In case of Domestic Emergency Operation an Ongoing Emergency should be linked also.',
  threeWProjectType: 'Project Type',
  threeWStatus: 'Status',
  // not used -   threeWCurrentOperation: 'IFRC supported Operation',
  threeWDisasterType: 'Disaster Type',
  // not used -   threeWOperationType: 'Operation Type',
  threeWPrimarySector: 'Primary Sector',
  threeWTags: 'Tags',
  threeWTagsTooltip: 'Projects are often multi-sector. The primary sector can be associated to sector ‘tags’.',
  threeWYear: 'Year',
  // not used -   threeWTargeted: 'Targeted',
  threeWPeopleTargeted: 'People Targeted',
  threeWMale: 'Male',
  threeWFemale: 'Female',
  threeWOther: 'Other',
  threeWTotal: 'Total',
  // not used -   threeWReached: 'Reached',
  threeWPeopleReached1: 'People Reached',
  threeWPeopleReached2: 'Services provided to people in need',
  threeWTargetMale: 'Male targeted',
  threeWTargetFemale: 'Female targeted',
  threeWTargetOther: 'Other targeted',
  threeWTargetTotal: 'Total targeted',
  threeWReachedMale: 'Male reached',
  threeWReachedFemale: 'Female reached',
  threeWReachedOther: 'Other reached',
  threeWReachedTotal: 'Total reached',
  threeWAddProject: 'Add 3W Project',
  threeWInCountryTabLabel: 'Projects in {countryName}',
  threeWNSProjectTabLabel: '{societyName} Projects',
  threeWLoginMessage: 'Login to see more details',
  threeWKeyFigureActiveNSTitle: 'Active National Societies',
  threeWKeyFigureTargetedPopulationTitle: 'Targeted Population',
  threeWKeyFigureTotalProjectsTitle: 'Total Projects',
  threeWKeyFigureProgrammeTypeTitle: 'Programme Type',
  threeWKeyFigureOngoingProjectBudgetTitle: 'Total Budget (CHF) for Ongoing Projects',
  threeWKeyFigureStatusTitle: 'Project Status',
  threeWKeyFigureCountryActivityTitle: 'Countries where NS has reported projects',
  threeWTopNoLoginMessage: 'To view all the project details, {loginLink} with your RCRC credentials',
  threeWBottomNoLoginMessage: 'If you are a member of RCRC Movement, login with your credentials to see more details.',
  threeWOngoingProjectsTitle: 'Ongoing Projects',
  threeWViewAllProjectsLabel: 'View All Projects',
  threeWInCountryMapSidebarTitle: 'Projects by Province',
  threeWInCountryOtherProjectsText: 'Other ({numProjects} Projects)',
  threeWInCountryAddProvinceButtonLabel: 'Add Province',
  threeWInCountryProvinceProjectsText: '{provinceName} ({numProjects} Projects)',
  threeWInCountryTableLocalTitle: 'Local Projects by NS ({numProjects})',
  threeWInCountryTableOtherNSTitle: 'Projects by Other NS ({numProjects})',
  threeWSankeyDiagramTitle: 'Overview of Activities',
  threeWNSMapSidebarTitle: 'NS Projects by Country',
  threeWNSCountryProjectsText: '{countryName} ({numProjects} Projects)',
  threeWFilterSectors: 'Sectors',
  threeWFilterReceivingCountries: 'Receiving Countries',
  threeWFilterProjectTypes: 'Project Types',
  threeWFilterProgrammeTypes: 'Programme Types',
  threeWFilterTags: 'Tags',
  threeWFilterNS: 'National Societies',
  threeWFilterProvinces: 'Provinces',
  threeWEditProject: 'Edit Project',
  threeWUpdateMessage: 'Project Updated, Redirecting...',

  threeWTableProjectName: 'Project Name',
  threeWTableSector: 'Sector',
  threeWTableTotalBudget: 'Total Budget',
  threeWTableProgrammeType: 'Programme Type',
  threeWTableDisasterType: 'Disaster Type',
  threeWTablePeopleTargeted: 'People Targeted',
  threeWTablePeopleReached2: 'Services provided to people in need',
  threeWTablePeopleReached2HelpText: 'The figure displayed here is a sum of all individual services or interventions delivered as part of this emergency operation to people in need. Some people may have received more than one service or intervention.',
  threeWTableNS: 'National Society',
  threeWTableCountry: 'Receiving Country',
  threeWEmptySankeyMessage: 'Not enough data to view the chart!',
  threeWNSMapReportingNS: 'Reporting NS',
  threeWNSMapReceivingCountry: 'Receiving Country',
  threeWLastModifiedOn: 'Last Modified On',
  threeWLastModifiedBy: 'by {user}',

  projectFormReportingNational: 'Reporting National Society *',
  projectFormReportingHelpText: 'Select National Society (or other actor) that is carrying out the activity.',
  projectFormReportingTooltip: 'It can be either the National Society where the disaster has taken place or a different National Society that is carrying out an activity in support of the response.',
  projectFormReportingNationalContact: 'Contact Information',
  projectFormReportingNationalContactText: 'Who should be contacted for any coordination matters related to this project?',
  projectFormFetching: 'Fetching national societies...',
  projectFormCountryTitle: 'Country and Region / Province* ',
  projectFormCountryHelpText: 'Select the country and region where the disaster is taking place.',
  projectFormCountryTooltip: 'The region can be referred to as states, provinces, or Admin Level 1. Choose countrywide for activities that are not limited to specific places. If the project takes place on multiple regions please submit each region separately using the clone-function on the country view table',
  projectFormCountryLabel: 'Country',
  // not used -   projectFormCountryPlaceholder: 'Fetching countries...',
  projectFormDistrictLabel: 'Region / Province',
  projectFormDistrictFetching: 'Fetching regions...',
  projectFormDistrictSelect: 'Select region(s)',
  projectFormNoCountryDistrictPlaceholder: 'Select a Country to view it\'s Regions',
  projectFormTypeOfOperation: 'Type of Operation / Programme*',
  projectFormTypeOfOperationTooltip: 'The operation type can be either an Emergency Operation or a Programme. Emergency Operations are new efforts linked to a specific emergency. Programs are ongoing work linked to a disaster. \n\nIf you choose Domestic, Bilateral, or Multilateral Programme, select Disaster Type that best fits the situation. Disasters are often multifactorial. Please choose the type that makes the most sense, recognizing that disasters are often the result of many complex factors. \nIf you choose Bilateral Emergency Operation, then no additional info is required. \nIf you choose Multilateral Emergency Operation, then please identify linked IFRC Emergency Operation.',
  projectFormProgrammeType: 'Programme Type:',
  projectFormProgrammeTooltip: 'Select the Programme Type. Choose from the options of Domestic, Bilateral, Multilateral. If you choose Domestic Emergency Operation, then identify linked Ongoing Emergency.',
  // not used -   projectFormAll: 'All',
  projectFormSelectAllDistricts: 'Select all districts',
  projectFormOperationType: 'Operation Type',
  projectFormProgrammeTypeLabel: 'Programme Type',
  projectFormNoCountryOperationPlaceholder: 'Select a Country to view it\'s current Operations',
  projectFormFetchingCurrentOperationPlaceholder: 'Fetching current Operations...',
  projectFormCurrentOperation: 'IFRC supported Operation*',
  projectFormCurrentEmergency: 'Current Emergency Operation*',
  projectFormCurrentEmergencyHelpText: 'The list is populated from current emergency operations related to the selected country. If necessary, create the related emergency through a field report',
  // not used -   projectFormFetchingEvents: 'Fetching events...',
  projectFormDisasterType: 'Disaster Type',
  projectFormDisasterTypeMandatory: 'Disaster Type*',
  projectFormDisasterTypeDefaultPlaceholder: 'Select a Disaster type',
  projectFormFetchingDisasterTypePlaceholder: 'Fetching Disaster Types...',
  projectFormOperationDefaultPlaceholder: 'Select an Operation',
  projectFormDisasterTypePlaceholder: 'Select an operation to view it\'s disaster type',
  projectFormProjectName: 'Project Name*',
  projectFormHelpText: 'Enter a name that differentiates your activity or project from other initiatives taking place in the response.',
  projectFormTooltip: 'The 3w system does allow for duplicate activities projects with the same name, but please choose a descriptive and original title.',
  projectFormDescription: 'Project Description',
  projectFormDescriptionHelpText: 'Enter a short narrative text about the project.',
  projectFormDescriptionTooltip: 'Even links can be inserted into this part, pointing to the public documentation, if exist.',
  projectFormSectorTitle: 'Sector and Tagging',
  projectFormPrimarySector: 'Primary Sector:',
  projectFormPrimarySectorText: 'Choose the sector that best represents the activity or project.',
  projectFormTagging: 'Tagging:',
  projectFormTaggingText: 'Projects are often multi-sector. After choosing the primary sector, feel free to add additional sector ‘tags’.',
  projectFormTaggingTooltip: 'CEA - Community engagement and accountability is a set of communication and participation activities that help put communities at the centre of the response. \n \nDRR - Disaster risk reduction is the concept and practice of reducing disaster risks through systemic efforts. It encompasses a broad range of activities – from ensuring that legislative and policy approaches reflect known hazards, to community-based initiatives and technical solutions such as early warning systems. \n \nEducation - Educational programming for people affected by disasters. \n \nHealth - Immediate assistance for disaster-affected people and longer-term activities that save lives and improve health outcomes. Separated into clinical and public health. \n \nLivelihood and basic needs - Livelihoods are the capabilities, assets and activities required for generating income and securing a basic means of living. \n \nMigration - Aid and protection for migrants and displaced people, in countries of origin, transit and destination, whatever their legal status. \n\nNS Strengthening - Support to the auxiliary role, strategy, governance and accountability; strengthening areas such as financial management, communications, fundraising; increase volunteer engagement; improve external relations; or ramp up their preparedness for responding to emergencies or improve the planning and execution of programmes and services they provide. \n \nPGI - Protection, gender and inclusion (PGI) in emergencies including sexual and gender-based violence and disability inclusion. \n \nShelter - Immediate and long term shelter assistance.  \n\nWASH - Water, sanitation and hygiene support. \n \n \nIt is possible to add none, one or many tags using the definitions listed above. For COVID-19 related projects please add the COVID-19 tag',
  projectFormPrimarySectorSelect: 'Primary Sector* ',
  projectFormSecondarySectorLabel: 'Tagging',
  projectFormMultiLabel: 'Start and End Dates* ',
  projectFormMultiLabelHelpText: 'Choose the date when the work on the activity or project begins',
  projectFormMultiLabelTooltip: 'Choose the date when the project is likely to end. Remember, you can easily return and edit this data if plans evolve.',
  projectFormStartDate: 'Start Date',
  projectFormEndDate: 'End Date',
  projectFormBudgetTitle: 'Budget and Status*',
  projectFormBudget: 'Budget:',
  projectFormBudgetText: 'Enter the budget for the activity or project.',
  projectFormProjectStatus: 'Project status:',
  projectFormProjectStatusText: 'The project status (planned and ongoing) is automatically defined by the current date and the submitted project timeline.',
  projectFormProjectTooltip: 'The budget includes the total costs for the listed activity or project. \nThe project can be marked completed, which makes the people reached a required value.',
  projectFormProjectBudget: 'Project Budget (CHF)',
  projectFormActualExpenditure: 'Actual Expenditure (CHF)',
  projectFormProjectCompleted: 'Completed',
  projectFormProjectStatusTitle: 'Project Status',
  projectFormPeopleTargeted: 'People Targeted',
  projectFormPeopleTargetedHelpText: 'Enter the number of people that the project plans to reach through the work.',
  projectFormPeopleTargetedTooltip: 'The options are: \nMale - People who identify as having the male gender \nFemale - People who identify as having the female gender \nOther - Other can include data such as “other sex/gender”, “undisclosed”, “unknown”, etc \nTotal - The total number of people included in the subcategories above',
  projectFormMale: 'Male',
  projectFormFemale: 'Female',
  projectFormOther: 'Other',
  projectFormTotal: 'Total',
  projectFormTotalRequired: 'Total*',
  projectFormPeopleReached2: 'Services provided to people in need',
  projectFormPeopleReachedHelpText: 'Enter the number of people reached (male, female, other – or only total) according to the definitions above.',
  projectFormPeopleReachedTooltip: 'Please follow the Counting People Reached guidelines as establishing the Federation-wide Databank and Reporting System.',
  projectFormPeopleReachedMale: 'Male',
  projectFormPeopleReachedFemale: 'Female',
  projectFormPeopleReachedOther: 'Other',
  projectFormProjectVisibility: 'Project visibility*',
  projectFormProjectVisibilityHelpText: 'Enter the desired visibility of the project',
  projectFormProjectVisibilityTooltip: 'The IFRC Only option limits viewing to only those vetted IFRC members who are logged into the GO platform and have the required permissions to view the data. Most programs should be in public mode, and we should only use the IFRC Only option in limited sensitive contexts where issues such as protection concerns are present. As with the wider GO Platform, there is no place for Personal or Community Identifiable data on this type of coordination platform. Sensitive data or information that could jeopardize the safety of staff or project participants should not be shared.',
  // not used -   projectFormError: 'There was an error submitting the request!',
  projectFormSubmit: 'Submit',
  projectFormSubmitting: 'Submitting...',
  projectFormModalTitle: 'Red Cross / Red Crescent activities',
  // not used -   projectFormModalClose: 'Close',
  projectFormNonFieldError: 'Please correct all the errors above before submission',
  projectFormFailedToSubmit: 'Failed to submit project: {message}',
  projectFormAnnually: 'and Budget – Annually',

  threeWPageTitle: 'IFRC GO - 3W Details',
  threeWEditPageTitle: 'IFRC GO - Edit 3W',
};

export type ThreeWStrings = typeof threeW;

export default threeW;
