# ssh-keygen -t rsa -b 4096 -C ifrcgo/go-frontend -f deploy_key
version: 2
jobs:
  build:
    docker:
      - image: node:7

    working_directory: ~/repo

    environment:
      - STAGING_BRANCH: develop
      - PRODUCTION_BRANCH: master
      - GH_REF: git@github.com:ifrcgo/go-frontend.git
      - GH_NAME: "Development Seed"
      - GH_EMAIL: "dev@developmentseed.org"

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

      - add_ssh_keys:
          fingerprints:
            - ""

      - run:
          name: Building site
          command: |
            if [ "${CIRCLE_BRANCH}" == "${STAGING_BRANCH}" ]; then
              yarn build-staging
            elif [ "${CIRCLE_BRANCH}" == "${PRODUCTION_BRANCH}" ]; then
              yarn build-prod
            else
              echo "Skip building site"
            fi

      - run:
          name: Deploy to Azure Blob Storage
          command: |
            if [ "${CIRCLE_BRANCH}" == "${STAGING_BRANCH}" ]; then
              yarn deploy-staging
            elif [ "${CIRCLE_BRANCH}" == "${PRODUCTION_BRANCH}" ]; then
              yarn deploy-prod
            else
              echo "Skip deploying to Azure Blob Storage"
            fi
