export const CountryMatches = {
"af": [['14','44','158'], ['Afghanistan','Central African Republic','South Africa']],
"al": [['15','16'], ['Albania','Algeria']],
"an": [['17','18','19'], ['Andorra','Angola','Antigua and Barbuda']],
"ar": [['20','21','149','206','2'], ['Argentina','Armenia','Saudi Arabia','Syrian Arab Republic','United Arab Emirates']],
"au": [['22','23'], ['Australia','Austria']],
"az": [['200'], ['Azerbaijan']],
"ba": [['25','26','27','28'], ['Bahamas','Bahrain','Bangladesh','Barbados']],
"be": [['29','30','31','209'], ['Belarus','Belgium','Belize','Benin']],
"bh": [['234'], ['Bhutan']],
"bi": [['183'], ['Guinea-Bissau']],
"bo": [['33','197','34'], ['Bolivia','Bosnia and Herzegovina','Botswana']],
"br": [['35','36'], ['Brazil','Brunei Darussalam']],
"bu": [['37','181','39'], ['Bulgaria','Burkina Faso','Burundi']],
"ca": [['43','40','41','42'], ['Cabo Verde','Cambodia','Cameroon','Canada']],
"ce": [['44'], ['Central African Republic']],
"ch": [['45','46','47'], ['Chad','Chile','China']],
"co": [['48','186','184','211','51','187','182'], ['Colombia','Comoros','Congo','Cook Islands','Costa Rica','Democratic Republic of Congo','Côte d\'Ivoire']],
"cr": [['53'], ['Croatia']],
"cu": [['54'], ['Cuba']],
"cy": [['228'], ['Cyprus']],
"cz": [['55'], ['Czech Republic']],
"cô": [['182'], ['Côte d\'Ivoire']],
"da": [['36'], ['Brunei Darussalam']],
"de": [['56','193','187'], ['Denmark','Democratic People\'s Republic of Korea','Democratic Republic of Congo']],
"dj": [['57'], ['Djibouti']],
"do": [['58','59'], ['Dominica','Dominican Republic']],
"ec": [['60'], ['Ecuador']],
"eg": [['61'], ['Egypt']],
"el": [['62'], ['El Salvador']],
"em": [['2'], ['United Arab Emirates']],
"eq": [['63'], ['Equatorial Guinea']],
"er": [['188'], ['Eritrea']],
"es": [['64','163'], ['Estonia','Eswatini, Kingdom of']],
"et": [['65'], ['Ethiopia']],
"fa": [['181'], ['Burkina Faso']],
"fi": [['66','67'], ['Fiji','Finland']],
"fr": [['68'], ['France']],
"ga": [['69','70'], ['Gabon','Gambia, Republic of The']],
"ge": [['71','72'], ['Georgia','Germany']],
"gh": [['73'], ['Ghana']],
"gr": [['74','75','179'], ['Greece','Grenada','Saint Vincent and the Grenadines']],
"gu": [['76','77','183','79','63','133'], ['Guatemala','Guinea','Guinea-Bissau','Guyana','Equatorial Guinea','Papua New Guinea']],
"ha": [['80'], ['Haiti']],
"he": [['197'], ['Bosnia and Herzegovina']],
"ho": [['274','81'], ['Holy See (Vatican City State)','Honduras']],
"hu": [['82'], ['Hungary']],
"ic": [['83'], ['Iceland']],
"in": [['84','85'], ['India','Indonesia']],
"ir": [['203','87','88'], ['Iran, Islamic Republic of','Iraq','Ireland']],
"is": [['222'], ['Israel']],
"it": [['89'], ['Italy']],
"iv": [['182'], ['Côte d\'Ivoire']],
"ja": [['90','91'], ['Jamaica','Japan']],
"jo": [['92'], ['Jordan']],
"ka": [['201'], ['Kazakhstan']],
"ke": [['93'], ['Kenya']],
"ki": [['94','177','3'], ['Kiribati','Saint Kitts and Nevis','United Kingdom']],
"ko": [['192','193'], ['Republic of Korea','Democratic People\'s Republic of Korea']],
"ku": [['97'], ['Kuwait']],
"ky": [['98'], ['Kyrgyzstan']],
"la": [['99','100','160'], ['Lao People\'s Democratic Republic','Latvia','Sri Lanka']],
"le": [['101','102','152','210'], ['Lebanon','Lesotho','Sierra Leone','Timor-Leste']],
"li": [['103','204','105','106'], ['Liberia','Libya','Liechtenstein','Lithuania']],
"lu": [['107','178'], ['Luxembourg','Saint Lucia']],
"ma": [['109','110','111','227','112','113','212','114','115','108','260'], ['Madagascar','Malawi','Malaysia','Maldives','Mali','Malta','Marshall Islands','Mauritania','Mauritius','North Macedonia','San Marino']],
"me": [['116'], ['Mexico']],
"mi": [['195'], ['Micronesia, Federated States of']],
"mo": [['202','117','194','270','119','120'], ['Moldova, Republic of','Monaco','Mongolia','Montenegro','Morocco','Mozambique']],
"my": [['121'], ['Myanmar']],
"na": [['122','251'], ['Namibia','Nauru']],
"ne": [['123','124','125','133','177'], ['Nepal','Netherlands','New Zealand','Papua New Guinea','Saint Kitts and Nevis']],
"ni": [['126','127','128','253'], ['Nicaragua','Niger','Nigeria','Niue']],
"no": [['108','129'], ['North Macedonia','Norway']],
"om": [['258'], ['Oman']],
"pa": [['131','130','205','132','133','134'], ['Pakistan','Palau','Palestine','Panama','Papua New Guinea','Paraguay']],
"pe": [['135'], ['Peru']],
"ph": [['136'], ['Philippines']],
"po": [['199','138'], ['Poland','Portugal']],
"pr": [['185'], ['Sao Tome and Principe']],
"qa": [['139'], ['Qatar']],
"re": [['192'], ['Republic of Korea']],
"ri": [['51'], ['Costa Rica']],
"ro": [['141'], ['Romania']],
"ru": [['142'], ['Russian Federation']],
"rw": [['143'], ['Rwanda']],
"sa": [['177','178','179','147','260','185','149'], ['Saint Kitts and Nevis','Saint Lucia','Saint Vincent and the Grenadines','Samoa','San Marino','Sao Tome and Principe','Saudi Arabia']],
"se": [['150','271','151'], ['Senegal','Serbia','Seychelles']],
"si": [['152','153'], ['Sierra Leone','Singapore']],
"sl": [['154','155'], ['Slovakia','Slovenia']],
"so": [['156','157','158','290'], ['Solomon Islands','Somalia','South Africa','South Sudan']],
"sp": [['159'], ['Spain']],
"sr": [['160'], ['Sri Lanka']],
"st": [['4'], ['United States']],
"su": [['161','180','290'], ['Sudan','Suriname','South Sudan']],
"sw": [['164','165'], ['Sweden','Switzerland']],
"sy": [['206'], ['Syrian Arab Republic']],
"ta": [['167','189'], ['Tajikistan','Tanzania, United Republic of']],
"th": [['169'], ['Thailand']],
"ti": [['210'], ['Timor-Leste']],
"to": [['170','171','185','172'], ['Togo','Tonga','Sao Tome and Principe','Trinidad and Tobago']],
"tr": [['172'], ['Trinidad and Tobago']],
"tu": [['173','175','213','174'], ['Tunisia','Turkmenistan','Tuvalu','Türkiye']],
"tü": [['174'], ['Türkiye']],
"ug": [['176'], ['Uganda']],
"uk": [['1','3'], ['Ukraine','United Kingdom']],
"un": [['2','3','4'], ['United Arab Emirates','United Kingdom','United States']],
"ur": [['5'], ['Uruguay']],
"us": [['4'], ['United States']],
"uz": [['6'], ['Uzbekistan']],
"va": [['7','274'], ['Vanuatu','Holy See (Vatican City State)']],
"ve": [['8'], ['Venezuela']],
"vi": [['191','179'], ['Viet Nam','Saint Vincent and the Grenadines']],
"ye": [['10'], ['Yemen']],
"za": [['12'], ['Zambia']],
"zi": [['13'], ['Zimbabwe']]};
